import SwiftUI

public extension Notification.Name {
    static let dofficeRefresh = Notification.Name("dofficeRefresh")
    static let dofficeNewTab = Notification.Name("dofficeNewTab")
    static let dofficeCloseTab = Notification.Name("dofficeCloseTab")
    static let dofficeSelectTab = Notification.Name("dofficeSelectTab")
    static let dofficeToggleSplit = Notification.Name("dofficeToggleSplit")
    static let dofficeExportLog = Notification.Name("dofficeExportLog")
    static let dofficeRestartSession = Notification.Name("dofficeRestartSession")
    static let dofficeNextTab = Notification.Name("dofficeNextTab")
    static let dofficePreviousTab = Notification.Name("dofficePreviousTab")
    static let dofficeCancelProcessing = Notification.Name("dofficeCancelProcessing")
    static let dofficeClearTerminal = Notification.Name("dofficeClearTerminal")
    static let dofficeToggleOffice = Notification.Name("dofficeToggleOffice")
    static let dofficeToggleTerminal = Notification.Name("dofficeToggleTerminal")
    static let dofficeClaudeNotInstalled = Notification.Name("dofficeClaudeNotInstalled")
    static let dofficeTabCycleCompleted = Notification.Name("dofficeTabCycleCompleted")
    static let dofficeRoleNotice = Notification.Name("dofficeRoleNotice")
    static let dofficeSessionStoreDidChange = Notification.Name("dofficeSessionStoreDidChange")
    static let dofficeScrollToBlock = Notification.Name("dofficeScrollToBlock")
    static let dofficeCommandPalette = Notification.Name("dofficeCommandPalette")
    static let dofficeActionCenter = Notification.Name("dofficeActionCenter")
    static let dofficeOpenBrowser = Notification.Name("dofficeOpenBrowser")
    static let dofficeToggleBrowser = Notification.Name("dofficeToggleBrowser")
}
