type Locale = "ko" | "en";

let forcedLocale: Locale | null = null;

const catalog: Record<Locale, Record<string, string>> = {
  ko: {
    "sessions": "세션",
    "search": "검색",
    "cancel": "취소",
    "status.all": "전체",
    "status.processing": "작업 중",
    "status.completed": "완료",
    "status.idle": "유휴",
    "status.active": "활성",
    "status.attention": "확인 필요",
    "session.new": "새 세션 시작",
    "session.project": "프로젝트를 열고 바로\n작업을 시작합니다.",
    "session.no.match": "조건에 맞는\n세션이 없습니다",
    "session.no.match.hint": "필터를 바꾸거나 새\n세션을 시작해보세요.",
    "view.split": "분할",
    "view.office": "오피스",
    "view.strip": "스트립",
    "view.terminal": "터미널",
    "main.refresh": "새로고침",
    "action.finder": "Finder에서 열기",
    "action.copy.path": "경로 복사",
    "action.close.session": "세션 닫기",
    "sidebar.sort.recent": "최근 활동",
    "sidebar.sort.name": "이름순",
    "sidebar.sort.tokens": "토큰순",
    "sidebar.sort.status": "상태순",
    "sidebar.sort.label": "정렬",
    "sidebar.history.empty.title": "이전 기록이 없습니다",
    "sidebar.history.empty.message": "작업을 한 번 시작하면 최근 세션이 여기에 정리됩니다.",
    "sidebar.time.just.now": "방금",
    "sidebar.time.minutes.ago": "%d분 전",
    "sidebar.time.hours.ago": "%d시간 전",
    "sidebar.time.days.ago": "%d일 전",
    "overlay.action.center": "확인 센터",
    "overlay.action.center.subtitle": "승인 대기, 오류, 완료 상태를 한 곳에서 확인합니다.",
    "overlay.pending.approval": "승인 대기",
    "overlay.needs.attention": "확인 필요",
    "overlay.in.progress": "작업 중",
    "overlay.completed": "완료",
    "overlay.all.normal": "모든 세션이 정상입니다",
    "overlay.new.session": "새 세션",
    "overlay.refresh.session": "세션 새로고침",
    "overlay.split.view": "분할 뷰",
    "overlay.office.view": "오피스 뷰",
    "overlay.strip.view": "스트립 뷰",
    "overlay.terminal.view": "터미널 뷰",
    "overlay.go.to.session": "세션 이동",
    "overlay.search.commands": "명령어 검색...",
    "overlay.navigate": "탐색",
    "overlay.execute": "실행",
    "overlay.close": "닫기",
    "terminal.approval.needed": "승인 필요",
    "terminal.deny": "거부",
    "terminal.approve": "승인",
    "terminal.no.session.title": "세션이 아직 없습니다",
    "terminal.no.session.message": "Cmd+T 또는 새 세션 시작 버튼으로 바로 작업을 시작할 수 있습니다.",
    "terminal.log.cleared": "🗑️ 로그가 초기화되었습니다",
    "terminal.no.running.task": "ℹ️ 실행 중인 작업이 없습니다",
    "terminal.copied.to.clipboard": "📋 클립보드에 복사되었습니다 (%d자)",
    "terminal.no.response.to.copy": "⚠️ 복사할 응답이 없습니다",
    "terminal.log.saved": "📁 로그 저장: %@",
    "terminal.log.save.failed": "⚠️ 저장 실패: %@",
    "terminal.model.current": "🤖 현재 모델: %@ %@\n사용법: /model <opus|sonnet|haiku|gpt-5.4|gemini-2.5-pro|gemini-2.5-flash>",
    "terminal.model.changed": "🤖 모델 변경: %@ %@",
    "terminal.effort.current": "💪 현재 노력 수준: %@ %@\n사용법: /effort <low|medium|high|max>",
    "slash.status.effort.changed": "💪 노력 수준 변경: %@ %@",
    "slash.status.output.current": "📺 현재 출력 모드: %@ %@\n사용법: /output <full|realtime|result>",
    "slash.status.output.unknown": "⚠️ 알 수 없는 모드: %@",
    "slash.status.output.changed": "📺 출력 모드 변경: %@ %@",
    "slash.status.permission.current": "🛡️ 현재 권한: %@ %@ — %@\n사용법: /permission <bypass|auto|default|plan|edits>",
    "slash.status.permission.unknown": "⚠️ 알 수 없는 모드: %@",
    "slash.status.permission.changed": "🛡️ 권한 변경: %@ %@ — %@",
    "slash.status.budget.current": "💰 현재 예산: %@\n사용법: /budget <금액|off>",
    "slash.status.budget.removed": "💰 예산 제한 해제",
    "slash.status.budget.invalid": "⚠️ 올바른 금액을 입력하세요",
    "slash.status.budget.set": "💰 최대 예산 설정: $%@",
    "slash.status.system.current": "📝 시스템 프롬프트:\n%@",
    "slash.status.system.none": "(없음)",
    "slash.status.system.cleared": "📝 시스템 프롬프트 초기화",
    "slash.status.system.set": "📝 시스템 프롬프트 설정:\n%@",
    "slash.status.worktree.toggle": "🌳 워크트리 모드: %@",
    "slash.status.chrome.toggle": "🌐 크롬 연동: %@",
    "slash.status.brief.toggle": "✂️ 간결 모드: %@",
    "slash.status.stats.title": "📊 세션 통계",
    "slash.status.stats.worker": "├ 작업자: %@ (%@)",
    "slash.status.stats.model": "├ 모델: %@ %@ · %@ %@",
    "slash.status.stats.elapsed": "├ 경과: %dm %ds",
    "slash.status.stats.tokens": "├ 토큰: %@ (입력 %@ / 출력 %@)",
    "slash.status.stats.cost": "├ 비용: $%@",
    "slash.status.stats.prompts": "├ 프롬프트: %d회",
    "slash.status.stats.commands": "├ 명령: %d개 · 에러: %d개",
    "slash.status.stats.blocks": "├ 블록: %d개",
    "slash.status.stats.files": "└ 파일 변경: %d개",
    "terminal.preset.balanced": "기본 작업",
    "terminal.preset.planfirst": "플랜 우선",
    "terminal.preset.safereview": "안전 검토",
    "terminal.preset.parallelbuild": "병렬 구현",
    "terminal.preset.balanced.desc": "일반 개발 시작",
    "terminal.preset.planfirst.desc": "계획만 먼저 정리",
    "terminal.preset.safereview.desc": "보수적 권한으로 검토",
    "terminal.preset.parallelbuild.desc": "여러 터미널로 분배",
    "terminal.config.project": "프로젝트",
    "terminal.config.project.subtitle": "경로만 입력해도 세션을 만들 수 있습니다.",
    "terminal.config.execution": "실행 설정",
    "terminal.config.execution.subtitle": "모델, 추론 강도, 권한 모드를 같은 규칙으로 정리했습니다.",
    "terminal.config.model": "모델",
    "terminal.config.permission": "권한",
    "terminal.config.terminal": "터미널",
    "terminal.config.terminal.subtitle": "작업을 나눌 때만 여러 개를 선택하면 됩니다.",
    "terminal.config.advanced": "고급 옵션",
    "terminal.config.advanced.desc": "예산, 워크트리, 도구 제한 같은 세부 옵션",
    "output.mode.full": "전체",
    "output.mode.realtime": "실시간",
    "output.mode.resultOnly": "결과만",
    "perm.acceptEdits": "수정만 허용",
    "perm.acceptEdits.desc": "파일 수정 권한 자동 승인",
    "perm.bypass": "전체 허용",
    "perm.bypass.desc": "모든 권한 자동 승인",
    "perm.auto": "자동",
    "perm.auto.desc": "상황에 따라 자동 판단",
    "perm.default": "기본",
    "perm.default.desc": "위험 명령 승인 필요",
    "perm.plan": "계획만",
    "perm.plan.desc": "계획만 세우고 실행 안함",
    "slash.toggle.on": "켜짐",
    "slash.toggle.off": "꺼짐",
    "custom.open.project": "프로젝트 열기",
    "custom.reveal.explorer": "탐색기에서 보기",
    "custom.remove.session": "세션 제거",
    "custom.action.center.empty.detail": "현재 검토가 필요한 세션이 없습니다.",
    "custom.pending.approval.waiting": "권한 승인을 기다리고 있습니다.",
    "custom.go": "이동",
    "custom.no.branch": "브랜치 없음",
    "custom.tokens.suffix": "tokens",
    "custom.new.session.subtitle": "프로젝트, 세션 프로필, Claude 실행 기본값을 한 번에 설정합니다.",
    "custom.project.path": "프로젝트 경로",
    "custom.agent": "에이전트",
    "custom.agent.claude": "Claude",
    "custom.agent.codex": "Codex",
    "custom.agent.gemini": "Gemini",
    "custom.display.name": "표시 이름",
    "custom.initial.prompt": "초기 프롬프트",
    "custom.browse": "찾아보기",
    "custom.create.session": "세션 만들기",
    "custom.favorites": "즐겨찾기",
    "custom.recent": "최근",
    "custom.no.favorite.projects": "즐겨찾기 프로젝트가 없습니다.",
    "custom.no.recent.projects": "최근 프로젝트가 없습니다.",
    "custom.session.config": "세션 설정",
    "custom.system.prompt": "시스템 프롬프트",
    "custom.max.budget": "최대 예산 USD",
    "custom.session.name": "세션 이름",
    "custom.fallback.model": "대체 모델",
    "custom.continue.session": "이전 세션 이어가기",
    "custom.use.worktree": "워크트리 사용",
    "custom.enable.chrome": "크롬 연동 켜기",
    "custom.enable.brief": "간결 출력 켜기",
    "custom.fork.on.run": "실행 시 포크",
    "custom.codex.sandbox": "Codex 샌드박스",
    "custom.codex.approval": "Codex 승인 정책",
    "custom.codex.sandbox.readonly": "읽기 전용",
    "custom.codex.sandbox.workspace": "워크스페이스 쓰기",
    "custom.codex.sandbox.danger": "전체 접근",
    "custom.codex.approval.untrusted": "신뢰 안 함",
    "custom.codex.approval.request": "요청 시",
    "custom.codex.approval.never": "허용 안 함",
    "custom.plugin.dirs": "플러그인 디렉터리",
    "custom.no.plugin.dirs": "추가된 플러그인 폴더가 없습니다.",
    "custom.add.plugin.dir": "플러그인 폴더 추가",
    "custom.plugin.marketplace": "플러그인 마켓",
    "custom.open.marketplace": "URL 열기",
    "custom.project.name.placeholder": "프로젝트 이름",
    "custom.initial.prompt.placeholder": "Claude에게 맡길 작업을 입력하세요",
    "custom.session.name.placeholder": "선택 사항",
    "custom.fallback.model.placeholder": "선택 사항",
    "custom.system.prompt.placeholder": "세션 시작 시 추가할 시스템 프롬프트",
    "custom.command.no.matches": "일치하는 항목이 없습니다",
    "custom.command.try.keyword": "다른 키워드로 다시 검색해보세요.",
    "custom.command.footer": "↑↓ 탐색 · Enter 실행 · Esc 닫기",
    "custom.title.subtitle": "Claude Code Manager",
    "custom.start.new.session": "새 세션 시작",
    "custom.token.usage": "토큰 사용량",
    "custom.token.leaderboard": "토큰 순위",
    "custom.history": "기록",
    "custom.no.token.usage": "아직 토큰 사용 기록이 없습니다.",
    "custom.no.launch.history": "실행 기록이 없습니다.",
    "custom.active": "활성",
    "custom.processing": "작업 중",
    "custom.attention": "확인 필요",
    "custom.completed": "완료",
    "custom.approval.needed": "승인 필요",
    "custom.no.sessions": "세션 없음",
    "custom.clear.filter": "새 세션을 만들거나 필터를 바꿔보세요.",
    "custom.path.open": "열기",
    "custom.path.reveal": "표시",
    "custom.path.copy": "경로 복사",
    "custom.export.log": "로그 저장",
    "custom.filter": "필터",
    "custom.files": "파일",
    "custom.search.log": "로그 검색",
    "custom.model": "모델",
    "custom.effort": "노력 수준",
    "custom.output": "출력",
    "custom.errors": "오류",
    "custom.no.recent.activity": "최근 활동이 없습니다.",
    "custom.session.stats": "세션 통계",
    "custom.session.config.title": "세션 설정",
    "custom.no.session.errors": "이 세션에는 기록된 오류가 없습니다.",
    "custom.no.session.files": "이 세션에는 추적된 파일 변경이 없습니다.",
    "custom.slash.commands": "슬래시 명령어",
    "custom.restored.session": "이전 세션을 복구했습니다. 진행 중이던 작업은 자동으로 재개되지 않습니다.",
    "custom.permission.denied": "권한이 거부되었습니다.",
    "custom.stopped": "중지됨",
    "custom.slash.empty": "슬래시 명령이 비어 있습니다. 사용 가능한 명령은 /help 를 실행하세요.",
    "custom.cancelled.active.session": "실행 중인 세션 작업을 취소했습니다.",
    "custom.stopped.active.session": "실행 중인 세션 작업을 중지했습니다.",
    "custom.unknown.command": "알 수 없는 명령어: /%@. 사용 가능한 명령은 /help 를 실행하세요.",
    "custom.continue.enabled": "이어가기 모드가 켜졌습니다. 다음 실행에서 Claude continue 모드를 요청합니다.",
    "custom.resume.enabled": "세션 %@ 에 대한 resume 모드가 켜졌습니다.",
    "custom.fork.enabled": "다음 실행에서 fork-session 모드가 켜졌습니다.",
    "custom.session.name.current": "세션 이름: %@",
    "custom.session.name.updated": "세션 이름이 %@ 로 변경되었습니다.",
    "custom.none": "없음",
    "custom.elapsed": "경과",
    "custom.resume.session.id": "재개 세션 ID",
    "office.zone.main": "메인 오피스",
    "office.zone.pantry": "팬트리",
    "office.zone.meeting": "미팅룸",
    "office.hud.overview": "오피스 개요",
    "office.hud.empty": "세션을 선택하면 하단에서 세부 상태를 확인할 수 있습니다.",
    "git.section.branches": "브랜치",
    "git.section.remotes": "원격",
    "git.section.tags": "태그",
    "git.section.stashes": "스태시",
    "git.section.commit.detail": "커밋 상세",
    "git.search.placeholder": "커밋, 작성자, ref 검색",
    "custom.browser": "Browser",
    "custom.usage": "USAGE",
    "custom.level": "LEVEL",
    "custom.characters": "캐릭터 관리",
    "custom.accessories": "악세서리",
    "custom.reports": "보고서",
    "custom.achievements": "도전과제",
    "custom.settings": "설정",
    "custom.lock": "잠금",
    "custom.direct.chat": "직접 입력",
    "custom.browser.empty": "북마크가 아직 없습니다.",
    "custom.browser.new.tab": "New Tab",
    "custom.browser.bookmarks": "북마크",
    "custom.browser.dev": "DEV",
    "custom.browser.search.placeholder": "URL 입력 또는 Google 검색",
    "custom.grid": "Grid",
    "custom.single": "Single",
    "custom.git": "Git",
    "custom.split.horizontal": "가로 분할",
    "custom.split.vertical": "세로 분할",
    "custom.split.close": "분할 닫기",
    "settings.title": "설정",
    "settings.tab.general": "일반",
    "settings.tab.theme": "화면",
    "settings.tab.office": "오피스",
    "settings.tab.tokens": "토큰",
    "settings.tab.data": "데이터",
    "settings.tab.template": "양식",
    "settings.tab.plugins": "플러그인",
    "settings.tab.support": "후원하기",
    "settings.tab.security": "보안",
    "settings.tab.shortcuts": "단축키",
    "settings.section.profile": "프로필",
    "settings.field.app.name": "앱 이름",
    "settings.field.company.name": "회사 이름",
    "settings.field.secret.key": "시크릿 키",
    "settings.field.secret.placeholder": "mac 프로젝트의 숨김 해금 키",
    "settings.action.apply": "적용",
    "settings.section.language": "언어 / Language",
    "settings.language.system": "시스템",
    "settings.language.ko": "한국어",
    "settings.language.en": "English",
    "settings.language.ja": "日本語",
    "settings.section.terminal": "터미널",
    "settings.option.raw.terminal": "일반 터미널",
    "settings.option.raw.terminal.iterm": "일반 터미널 (iTerm)",
    "settings.option.auto.refresh": "자동 새로고침",
    "settings.option.replay.tutorial": "튜토리얼 다시보기",
    "settings.action.open": "열기",
    "settings.section.cli": "CLI 상태",
    "settings.cli.note": "설치 상태를 확인하고, 누락된 CLI는 바로 설치할 수 있습니다.",
    "settings.cli.refresh": "상태 다시 확인",
    "settings.cli.refreshing": "확인 중...",
    "settings.cli.refresh.done": "CLI 상태를 다시 확인했습니다.",
    "settings.cli.install": "설치",
    "settings.cli.installing": "설치 중...",
    "settings.cli.installed": "설치됨",
    "settings.cli.not.installed": "미설치",
    "settings.cli.version.installed": "설치됨 · %@",
    "settings.count.items": "%d개",
    "settings.theme.section.theme": "테마",
    "settings.theme.section.background": "배경 모드",
    "settings.theme.section.font.size": "글자 크기",
    "settings.theme.font.size.current": "현재 크기: %@",
    "settings.restart.language.confirm": "언어를 변경하면 앱이 다시 시작됩니다. 계속할까요?",
    "settings.restart.theme.confirm": "테마를 변경하면 앱이 다시 시작됩니다. 계속할까요?",
    "settings.restart.font.confirm": "글자 크기를 변경하면 앱이 다시 시작됩니다. 계속할까요?",
    "settings.office.section.layout": "레이아웃",
    "settings.office.layout.cozy": "라운지와 창이 살아있는 기본 사무실",
    "settings.office.layout.collab": "회의와 화이트보드 중심 협업형 배치",
    "settings.office.layout.focus": "집중 좌석과 조용한 흐름이 맞는 배치",
    "settings.office.section.camera": "카메라 시점",
    "settings.office.camera.overview": "전체",
    "settings.office.camera.focus": "포커스",
    "settings.tokens.section.usage": "사용량",
    "settings.tokens.note": "일일/주간 사용량과 예산 보호선을 같이 봅니다.",
    "settings.tokens.recommendation": "권장 하한은 예산 보호와 자동화 보호에 맞춘 mac 기본값입니다.",
    "settings.tokens.protection.title": "토큰 보호",
    "settings.tokens.protection.enabled": "토큰 보호 활성화",
    "settings.tokens.protection.enabled.desc": "Provider별 세션 토큰 한도와 보호 차단을 함께 사용합니다.",
    "settings.tokens.protection.disabled.desc": "전역 보호가 꺼져 있습니다. Provider별 세션 한도는 계속 적용됩니다.",
    "settings.tokens.provider.limits": "Provider별 세션 토큰 한도 (0 = 무제한)",
    "settings.tokens.provider.claude": "Claude",
    "settings.tokens.provider.codex": "Codex",
    "settings.tokens.provider.gemini": "Gemini",
    "settings.tokens.plan.title": "Provider 플랜 계산기",
    "settings.tokens.plan.subtitle": "플랜을 고르면 주간 한도와 권장 세션 한도를 같이 채웁니다.",
    "settings.tokens.plan.summary": "합산 한도 · 주 %@ / 일 %@",
    "settings.tokens.plan.active": "%@ · 주 %@",
    "settings.tokens.plan.none": "플랜 미설정",
    "settings.tokens.plan.weekly": "주 %@",
    "settings.tokens.plan.session.suggestion": "권장 세션 한도 %@",
    "settings.tokens.plan.clear": "초기화",
    "settings.tokens.limit.reached": "%@ 세션 한도 도달 · %@ / %@ tokens",
    "settings.tokens.limit.active": "현재 세션 한도 %@ tokens",
    "settings.tokens.today": "오늘",
    "settings.tokens.this.week": "이번 주",
    "settings.tokens.daily.limit": "일일 한도 ($)",
    "settings.tokens.session.limit": "세션별 한도 ($)",
    "settings.tokens.apply.recommended": "권장 하한 적용",
    "settings.tokens.clear.history": "토큰 이력 초기화",
    "settings.tokens.section.automation": "자동화 보호",
    "settings.tokens.parallel.agents": "AI 병렬 서브에이전트 허용",
    "settings.tokens.lightweight.sidebar": "경량 터미널 사이드바",
    "settings.tokens.review.max": "리뷰 최대",
    "settings.tokens.qa.max": "QA 최대",
    "settings.tokens.revision.limit": "수정 반복",
    "settings.data.section.storage": "저장 공간",
    "settings.data.storage.note": "총 저장 공간 약 %@ MB",
    "settings.data.sessions": "세션 기록",
    "settings.data.tokens": "토큰 이력",
    "settings.data.office.layout": "오피스 레이아웃",
    "settings.data.achievements": "업적 데이터",
    "settings.data.characters": "캐릭터 데이터",
    "settings.data.reports": "보고서",
    "settings.data.section.cache": "캐시 관리",
    "settings.data.cache.note": "오래된 캐시와 임시 데이터를 정리하면 보고서/브라우저 관련 응답 속도가 안정화됩니다.",
    "settings.data.cache.old": "오래된 캐시 삭제",
    "settings.data.delete.all": "전체 데이터 삭제",
    "settings.template.section.workflow": "워크플로 양식",
    "settings.template.section.editor": "편집기",
    "settings.template.using.current": "기본 양식 사용중 · %@",
    "settings.template.reset.current": "현재 양식 초기화",
    "settings.template.reset.all": "전체 양식 초기화",
    "settings.security.section.session": "세션 보호",
    "settings.security.lock.pin": "잠금 PIN",
    "settings.security.pin.placeholder": "PIN 입력",
    "settings.security.auto.lock": "자동 잠금",
    "settings.security.disabled": "사용 안함",
    "settings.security.minutes": "%d분",
    "settings.security.billing.alert": "결제일 알림",
    "settings.security.unset": "미설정",
    "settings.security.day": "%d일",
    "settings.security.lock.now": "지금 잠금",
    "settings.security.unlock.now": "잠금 해제",
    "settings.security.remove.pin": "PIN 제거",
    "settings.security.section.budget": "비용 제한",
    "settings.security.daily.limit": "일일 제한 ($)",
    "settings.security.session.limit": "세션별 제한 ($)",
    "settings.security.warn.threshold": "80% 도달 시 경고",
    "settings.security.section.protection": "보호 기능",
    "settings.security.detect.dangerous": "위험 명령 감지",
    "settings.security.protect.sensitive": "민감 파일 보호",
    "settings.security.export.log": "보호 로그 내보내기",
    "settings.security.clear.records": "보호 기록 삭제",
    "settings.plugins.section.add": "플러그인 추가",
    "settings.plugins.source.label": "URL / Brew / 로컬 경로",
    "settings.plugins.source.placeholder": "formula-name / user/tap/formula / https://... / ~/plugin",
    "settings.plugins.install": "설치",
    "settings.plugins.local.folder": "로컬 폴더",
    "settings.plugins.local.plugin": "로컬 플러그인",
    "settings.plugins.new.plugin": "새 플러그인",
    "settings.plugins.direct.download": "직접 다운로드",
    "settings.plugins.local.path": "로컬 경로",
    "settings.plugins.installed.summary": "설치된 플러그인 · %d개 설치 / %d개 활성",
    "settings.plugins.installed.tab": "설치됨 · %d",
    "settings.plugins.marketplace.tab": "마켓 · %d",
    "settings.plugins.installed.badge": "설치됨",
    "settings.plugins.installed.empty": "설치된 플러그인이 없습니다.",
    "settings.plugins.section.marketplace": "마켓플레이스",
    "settings.plugins.open.github": "Github 열기",
    "settings.plugins.search.placeholder": "플러그인 검색",
    "settings.support.section.title": "후원하기",
    "settings.support.note": "후원은 Windows 포트와 mac parity 작업 유지에 직접 사용됩니다.",
    "settings.support.copy": "복사",
    "settings.support.kakao": "카카오뱅크",
    "settings.support.kakao.desc": "카카오뱅크 앱 또는 웹 열기",
    "settings.support.toss": "토스",
    "settings.support.toss.desc": "토스 앱 또는 웹 열기",
    "settings.support.fallback.note": "앱을 열 수 없으면 공식 웹사이트로 이동합니다. 계좌는 자동 복사됩니다.",
    "settings.shortcuts.section.session": "세션",
    "settings.shortcuts.section.terminal": "터미널",
    "settings.shortcuts.section.view": "뷰 제어",
    "settings.shortcuts.refresh": "새로고침",
    "settings.shortcuts.new.session": "새 세션",
    "settings.shortcuts.close.session": "세션 닫기",
    "settings.shortcuts.sidebar.toggle": "사이드바 토글",
    "settings.shortcuts.task.approve": "작업 승인",
    "settings.shortcuts.task.deny": "작업 거절",
    "settings.shortcuts.pin.selected": "선택 세션 고정",
    "settings.shortcuts.filter.toggle": "필터 토글",
    "settings.shortcuts.file.panel": "파일 패널",
    "settings.shortcuts.command.palette": "Command Palette",
    "settings.shortcuts.action.center": "Action Center",
    "settings.shortcuts.split.view": "분할 뷰",
    "settings.shortcuts.office.view": "오피스 뷰",
    "settings.shortcuts.strip.view": "스트립 뷰",
    "settings.shortcuts.terminal.view": "터미널 뷰"
  },
  en: {}
};

catalog.en = {
  ...Object.fromEntries(Object.keys(catalog.ko).map((key) => [key, key])),
  "sessions": "SESSIONS",
  "search": "Search",
  "cancel": "Cancel",
  "status.all": "All",
  "status.processing": "Processing",
  "status.completed": "Completed",
  "status.idle": "Idle",
  "status.active": "Active",
  "status.attention": "Needs Attention",
  "session.new": "Start New Session",
  "session.project": "Open a project and start working immediately.",
  "session.no.match": "No matching sessions",
  "session.no.match.hint": "Change the filter or start a new session.",
  "view.split": "Split",
  "view.office": "Office",
  "view.strip": "Strip",
  "view.terminal": "Terminal",
  "main.refresh": "Refresh",
  "action.finder": "Open in Explorer",
  "action.copy.path": "Copy Path",
  "action.close.session": "Close Session",
  "overlay.action.center": "Action Center",
  "overlay.action.center.subtitle": "Review approvals, errors, running work, and recently completed sessions.",
  "overlay.pending.approval": "Pending Approval",
  "overlay.needs.attention": "Needs Attention",
  "overlay.in.progress": "In Progress",
  "overlay.completed": "Completed",
  "overlay.all.normal": "All clear",
  "overlay.new.session": "New Session",
  "overlay.refresh.session": "Refresh Sessions",
  "overlay.split.view": "Split View",
  "overlay.office.view": "Office View",
  "overlay.strip.view": "Strip View",
  "overlay.terminal.view": "Terminal View",
  "overlay.go.to.session": "Go to session",
  "overlay.search.commands": "Search commands and sessions",
  "overlay.navigate": "navigate",
  "overlay.execute": "execute",
  "overlay.close": "close",
  "terminal.approval.needed": "Approval Needed",
  "terminal.deny": "Deny",
  "terminal.approve": "Approve",
  "terminal.no.session.title": "No sessions yet",
  "terminal.no.session.message": "Start working from Cmd+T or the new session button.",
  "terminal.preset.balanced": "Balanced",
  "terminal.preset.planfirst": "Plan First",
  "terminal.preset.safereview": "Safe Review",
  "terminal.preset.parallelbuild": "Parallel Build",
  "terminal.preset.balanced.desc": "Default coding session",
  "terminal.preset.planfirst.desc": "Start in plan mode",
  "terminal.preset.safereview.desc": "Higher effort, safer permissions",
  "terminal.preset.parallelbuild.desc": "High effort with worktree",
  "terminal.config.project": "Project",
  "terminal.config.project.subtitle": "You can start a session with only a path.",
  "terminal.config.execution": "Execution",
  "terminal.config.execution.subtitle": "Model, reasoning level, and permission mode.",
  "terminal.config.model": "Model",
  "terminal.config.permission": "Permission",
  "terminal.config.terminal": "Terminal",
  "terminal.config.terminal.subtitle": "Use multiple terminals only when you want to split work.",
  "terminal.config.advanced": "Advanced",
  "terminal.config.advanced.desc": "Budget, worktree, and tool restrictions.",
  "output.mode.full": "Full",
  "output.mode.realtime": "Realtime",
  "output.mode.resultOnly": "Result Only",
  "perm.acceptEdits": "Accept Edits",
  "perm.acceptEdits.desc": "Automatically approve file edits",
  "perm.bypass": "Bypass",
  "perm.bypass.desc": "Automatically approve all permissions",
  "perm.auto": "Auto",
  "perm.auto.desc": "Automatically decide by context",
  "perm.default": "Default",
  "perm.default.desc": "Risky commands still need approval",
  "perm.plan": "Plan",
  "perm.plan.desc": "Plan only, do not execute",
  "slash.toggle.on": "On",
  "slash.toggle.off": "Off",
  "custom.open.project": "Open Project",
  "custom.reveal.explorer": "Reveal in Explorer",
  "custom.remove.session": "Remove Session",
  "custom.action.center.empty.detail": "No sessions currently require review.",
  "custom.pending.approval.waiting": "Waiting for permission approval.",
  "custom.go": "Go",
  "custom.no.branch": "No branch",
  "custom.tokens.suffix": "tokens",
  "custom.new.session.subtitle": "Configure a project, session profile, and Claude execution defaults.",
  "custom.project.path": "Project Path",
  "custom.agent": "Agent",
  "custom.agent.claude": "Claude",
  "custom.agent.codex": "Codex",
  "custom.agent.gemini": "Gemini",
  "custom.display.name": "Display Name",
  "custom.initial.prompt": "Initial Prompt",
  "custom.browse": "Browse",
  "custom.create.session": "Create Session",
  "custom.favorites": "Favorites",
  "custom.recent": "Recent",
  "custom.no.favorite.projects": "No favorite projects yet.",
  "custom.no.recent.projects": "No recent projects yet.",
  "custom.session.config": "Session Config",
  "custom.system.prompt": "System Prompt",
  "custom.max.budget": "Max Budget USD",
  "custom.session.name": "Session Name",
  "custom.fallback.model": "Fallback Model",
  "custom.continue.session": "Continue previous session",
  "custom.use.worktree": "Use worktree",
  "custom.enable.chrome": "Enable Chrome integration",
  "custom.enable.brief": "Enable brief output",
  "custom.fork.on.run": "Fork on run",
  "custom.codex.sandbox": "Codex Sandbox",
  "custom.codex.approval": "Codex Approval",
  "custom.codex.sandbox.readonly": "Read Only",
  "custom.codex.sandbox.workspace": "Workspace Write",
  "custom.codex.sandbox.danger": "Danger Full Access",
  "custom.codex.approval.untrusted": "Untrusted",
  "custom.codex.approval.request": "On Request",
  "custom.codex.approval.never": "Never",
  "custom.plugin.dirs": "Plugin Dirs",
  "custom.no.plugin.dirs": "No plugin folders added.",
  "custom.add.plugin.dir": "Add Plugin Dir",
  "custom.plugin.marketplace": "Plugin Marketplace",
  "custom.open.marketplace": "Open URL",
  "custom.project.name.placeholder": "Project name",
  "custom.initial.prompt.placeholder": "What should Claude work on?",
  "custom.session.name.placeholder": "Optional",
  "custom.fallback.model.placeholder": "Optional",
  "custom.system.prompt.placeholder": "Append a system prompt for this session",
  "custom.command.no.matches": "No matches",
  "custom.command.try.keyword": "Try another keyword.",
  "custom.command.footer": "↑↓ navigate · Enter execute · Esc close",
  "custom.title.subtitle": "Claude Code Manager",
  "custom.start.new.session": "Start New Session",
  "custom.token.usage": "Token Usage",
  "custom.token.leaderboard": "Token Leaderboard",
  "custom.history": "History",
  "custom.no.token.usage": "No token usage yet.",
  "custom.no.launch.history": "No launch history yet.",
  "custom.active": "Active",
  "custom.processing": "Processing",
  "custom.attention": "Attention",
  "custom.completed": "Completed",
  "custom.approval.needed": "Approval Needed",
  "custom.no.sessions": "No sessions",
  "custom.clear.filter": "Create a new session or clear the current filter.",
  "custom.path.open": "Open",
  "custom.path.reveal": "Reveal",
  "custom.path.copy": "Copy Path",
  "custom.export.log": "Export Log",
  "custom.filter": "Filter",
  "custom.files": "Files",
  "custom.search.log": "Search log",
  "custom.model": "Model",
  "custom.effort": "Effort",
  "custom.output": "Output",
  "custom.errors": "Errors",
  "custom.no.recent.activity": "No recent activity.",
  "custom.session.stats": "Session Stats",
  "custom.session.config.title": "Session Config",
  "custom.no.session.errors": "No errors recorded for this session.",
  "custom.no.session.files": "No tracked file changes for this session.",
  "custom.slash.commands": "Slash Commands",
  "custom.restored.session": "Restored previous session. In-progress work did not resume automatically.",
  "custom.permission.denied": "Permission denied.",
  "custom.stopped": "Stopped",
  "custom.slash.empty": "Slash command is empty. Run /help for available commands.",
  "custom.cancelled.active.session": "Cancelled active session task.",
  "custom.stopped.active.session": "Stopped active session task.",
  "custom.unknown.command": "Unknown command: /%@. Run /help for available commands.",
  "custom.continue.enabled": "Continue mode enabled. The next run will request Claude continue mode.",
  "custom.resume.enabled": "Resume mode enabled for session %@.",
  "custom.fork.enabled": "Fork-session mode enabled for the next run.",
  "custom.session.name.current": "Session name: %@",
  "custom.session.name.updated": "Session name updated to %@.",
  "custom.none": "None",
  "custom.elapsed": "Elapsed",
  "custom.resume.session.id": "Resume Session ID",
  "office.zone.main": "Main office",
  "office.zone.pantry": "Pantry",
  "office.zone.meeting": "Meeting room",
  "office.hud.overview": "Office overview",
  "office.hud.empty": "Select a session to inspect its current office activity.",
  "git.section.branches": "Branches",
  "git.section.remotes": "Remotes",
  "git.section.tags": "Tags",
  "git.section.stashes": "Stashes",
  "git.section.commit.detail": "Commit detail",
  "git.search.placeholder": "Search commits, author, refs",
  "custom.session.explorer": "Session Explorer",
  "custom.search.project.placeholder": "Search project, path, worker",
  "custom.sort": "Sort",
  "custom.total": "Total",
  "custom.no.active.sessions": "No active sessions",
  "custom.processing.count": "Processing %d",
  "custom.attention.count": "Attention %d",
  "custom.completed.count": "Completed %d",
  "custom.shortcuts": "Ctrl+P palette · Ctrl+T new · Ctrl+J center · Ctrl+1-9 switch",
  "custom.layout.preset": "Layout preset",
  "custom.focus.view": "Focus view",
  "custom.browser": "Browser",
  "custom.usage": "USAGE",
  "custom.level": "LEVEL",
  "custom.characters": "Characters",
  "custom.accessories": "Accessories",
  "custom.reports": "Reports",
  "custom.achievements": "Achievements",
  "custom.settings": "Settings",
  "custom.lock": "Lock",
  "custom.direct.chat": "Direct Chat",
  "custom.browser.empty": "No bookmarks yet.",
  "custom.browser.new.tab": "New Tab",
  "custom.browser.bookmarks": "Bookmarks",
  "custom.browser.dev": "DEV",
  "custom.browser.search.placeholder": "Enter a URL or search Google",
  "custom.grid": "Grid",
  "custom.single": "Single",
  "custom.git": "Git",
  "custom.split.horizontal": "Split Horizontally",
  "custom.split.vertical": "Split Vertically",
  "custom.split.close": "Close Split",
  "settings.title": "Settings",
  "settings.tab.general": "General",
  "settings.tab.theme": "Display",
  "settings.tab.office": "Office",
  "settings.tab.tokens": "Tokens",
  "settings.tab.data": "Data",
  "settings.tab.template": "Template",
  "settings.tab.plugins": "Plugins",
  "settings.tab.support": "Support",
  "settings.tab.security": "Security",
  "settings.tab.shortcuts": "Shortcuts",
  "settings.section.profile": "Profile",
  "settings.field.app.name": "App Name",
  "settings.field.company.name": "Company Name",
  "settings.field.secret.key": "Secret Key",
  "settings.field.secret.placeholder": "Hidden unlock key from the mac project",
  "settings.action.apply": "Apply",
  "settings.section.language": "Language",
  "settings.language.system": "System",
  "settings.language.ko": "Korean",
  "settings.language.en": "English",
  "settings.language.ja": "Japanese",
  "settings.section.terminal": "Terminal",
  "settings.option.raw.terminal": "Raw Terminal",
  "settings.option.raw.terminal.iterm": "Raw Terminal (iTerm)",
  "settings.option.auto.refresh": "Auto Refresh",
  "settings.option.replay.tutorial": "Replay Tutorial",
  "settings.action.open": "Open",
  "settings.section.cli": "CLI Status",
  "settings.cli.note": "Check what is installed and install missing CLIs directly from here.",
  "settings.cli.refresh": "Refresh Status",
  "settings.cli.refreshing": "Refreshing...",
  "settings.cli.refresh.done": "CLI status refreshed.",
  "settings.cli.install": "Install",
  "settings.cli.installing": "Installing...",
  "settings.cli.installed": "Installed",
  "settings.cli.not.installed": "Not Installed",
  "settings.cli.version.installed": "Installed · %@",
  "settings.count.items": "%d items",
  "settings.theme.section.theme": "Theme",
  "settings.theme.section.background": "Background Mode",
  "settings.theme.section.font.size": "Font Size",
  "settings.theme.font.size.current": "Current size: %@",
  "settings.restart.language.confirm": "Changing the language will restart the app. Continue?",
  "settings.restart.theme.confirm": "Changing the theme will restart the app. Continue?",
  "settings.restart.font.confirm": "Changing the font size will restart the app. Continue?",
  "settings.office.section.layout": "Layout",
  "settings.office.layout.cozy": "Default office with lounge and windows",
  "settings.office.layout.collab": "Collaboration layout centered on meetings and whiteboards",
  "settings.office.layout.focus": "Layout tuned for focus seats and a quieter flow",
  "settings.office.section.camera": "Camera View",
  "settings.office.camera.overview": "Overview",
  "settings.office.camera.focus": "Focus",
  "settings.tokens.section.usage": "Usage",
  "settings.tokens.note": "Review daily and weekly usage with budget guardrails together.",
  "settings.tokens.recommendation": "Recommended minimums follow the mac defaults for budget and automation protection.",
  "settings.tokens.protection.title": "Token Protection",
  "settings.tokens.protection.enabled": "Enable Token Protection",
  "settings.tokens.protection.enabled.desc": "Use provider-specific session token limits and guardrails together.",
  "settings.tokens.protection.disabled.desc": "Global protection is off. Provider session limits still apply.",
  "settings.tokens.provider.limits": "Per-provider session token limits (0 = unlimited)",
  "settings.tokens.provider.claude": "Claude",
  "settings.tokens.provider.codex": "Codex",
  "settings.tokens.provider.gemini": "Gemini",
  "settings.tokens.plan.title": "Provider Plan Calculator",
  "settings.tokens.plan.subtitle": "Choose a plan to fill in weekly allowance and a suggested session cap together.",
  "settings.tokens.plan.summary": "Combined allowance · %@ weekly / %@ daily",
  "settings.tokens.plan.active": "%@ · %@ weekly",
  "settings.tokens.plan.none": "No plan selected",
  "settings.tokens.plan.weekly": "%@ weekly",
  "settings.tokens.plan.session.suggestion": "Suggested session cap %@",
  "settings.tokens.plan.clear": "Clear",
  "settings.tokens.limit.reached": "%@ session limit reached · %@ / %@ tokens",
  "settings.tokens.limit.active": "Current session limit %@ tokens",
  "settings.tokens.today": "Today",
  "settings.tokens.this.week": "This Week",
  "settings.tokens.daily.limit": "Daily Limit ($)",
  "settings.tokens.session.limit": "Per-Session Limit ($)",
  "settings.tokens.apply.recommended": "Apply Recommended Minimums",
  "settings.tokens.clear.history": "Reset Token History",
  "settings.tokens.section.automation": "Automation Guardrails",
  "settings.tokens.parallel.agents": "Allow AI Parallel Subagents",
  "settings.tokens.lightweight.sidebar": "Lightweight Terminal Sidebar",
  "settings.tokens.review.max": "Review Max",
  "settings.tokens.qa.max": "QA Max",
  "settings.tokens.revision.limit": "Revision Limit",
  "settings.data.section.storage": "Storage",
  "settings.data.storage.note": "Estimated total storage %@ MB",
  "settings.data.sessions": "Session Logs",
  "settings.data.tokens": "Token History",
  "settings.data.office.layout": "Office Layout",
  "settings.data.achievements": "Achievement Data",
  "settings.data.characters": "Character Data",
  "settings.data.reports": "Reports",
  "settings.data.section.cache": "Cache",
  "settings.data.cache.note": "Cleaning old cache and temp data helps stabilize report and browser responsiveness.",
  "settings.data.cache.old": "Clear Old Cache",
  "settings.data.delete.all": "Delete All Data",
  "settings.template.section.workflow": "Workflow Template",
  "settings.template.section.editor": "Editor",
  "settings.template.using.current": "Using default template · %@",
  "settings.template.reset.current": "Reset Current Template",
  "settings.template.reset.all": "Reset All Templates",
  "settings.security.section.session": "Session Protection",
  "settings.security.lock.pin": "Lock PIN",
  "settings.security.pin.placeholder": "Enter PIN",
  "settings.security.auto.lock": "Auto Lock",
  "settings.security.disabled": "Disabled",
  "settings.security.minutes": "%d min",
  "settings.security.billing.alert": "Billing Day Reminder",
  "settings.security.unset": "Unset",
  "settings.security.day": "Day %d",
  "settings.security.lock.now": "Lock Now",
  "settings.security.unlock.now": "Unlock",
  "settings.security.remove.pin": "Remove PIN",
  "settings.security.section.budget": "Budget Limits",
  "settings.security.daily.limit": "Daily Limit ($)",
  "settings.security.session.limit": "Per-Session Limit ($)",
  "settings.security.warn.threshold": "Warn at 80%",
  "settings.security.section.protection": "Protection Features",
  "settings.security.detect.dangerous": "Detect Dangerous Commands",
  "settings.security.protect.sensitive": "Protect Sensitive Files",
  "settings.security.export.log": "Export Protection Log",
  "settings.security.clear.records": "Clear Protection Records",
  "settings.plugins.section.add": "Add Plugin",
  "settings.plugins.source.label": "URL / Brew / Local Path",
  "settings.plugins.source.placeholder": "formula-name / user/tap/formula / https://... / ~/plugin",
  "settings.plugins.install": "Install",
  "settings.plugins.local.folder": "Local Folder",
  "settings.plugins.local.plugin": "Local Plugin",
  "settings.plugins.new.plugin": "New Plugin",
  "settings.plugins.direct.download": "Direct Download",
  "settings.plugins.local.path": "Local Path",
  "settings.plugins.installed.summary": "Installed Plugins · %d installed / %d active",
  "settings.plugins.installed.tab": "Installed · %d",
  "settings.plugins.marketplace.tab": "Marketplace · %d",
  "settings.plugins.installed.badge": "Installed",
  "settings.plugins.installed.empty": "No installed plugins yet.",
  "settings.plugins.section.marketplace": "Marketplace",
  "settings.plugins.open.github": "Open Github",
  "settings.plugins.search.placeholder": "Search plugins",
  "settings.support.section.title": "Support",
  "settings.support.note": "Support directly funds the Windows port and mac parity work.",
  "settings.support.copy": "Copy",
  "settings.support.kakao": "KakaoBank",
  "settings.support.kakao.desc": "Open KakaoBank app or website",
  "settings.support.toss": "Toss",
  "settings.support.toss.desc": "Open Toss app or website",
  "settings.support.fallback.note": "If the app cannot open, the official website is opened instead. The account number is copied automatically.",
  "settings.shortcuts.section.session": "Session",
  "settings.shortcuts.section.terminal": "Terminal",
  "settings.shortcuts.section.view": "View Controls",
  "settings.shortcuts.refresh": "Refresh",
  "settings.shortcuts.new.session": "New Session",
  "settings.shortcuts.close.session": "Close Session",
  "settings.shortcuts.sidebar.toggle": "Toggle Sidebar",
  "settings.shortcuts.task.approve": "Approve Task",
  "settings.shortcuts.task.deny": "Deny Task",
  "settings.shortcuts.pin.selected": "Pin Selected Session",
  "settings.shortcuts.filter.toggle": "Toggle Filter",
  "settings.shortcuts.file.panel": "File Panel",
  "settings.shortcuts.command.palette": "Command Palette",
  "settings.shortcuts.action.center": "Action Center",
  "settings.shortcuts.split.view": "Split View",
  "settings.shortcuts.office.view": "Office View",
  "settings.shortcuts.strip.view": "Strip View",
  "settings.shortcuts.terminal.view": "Terminal View",
  "custom.approval": "Approval",
  "custom.busy": "Busy",
  "custom.pin": "Pin",
  "custom.unpin": "Unpin",
  "custom.remove": "Remove",
  "custom.no.output": "No output yet.",
  "custom.no.session.selected": "No session selected.",
  "custom.send.prompt.placeholder": "Send a prompt to Claude",
  "custom.send.prompt": "Send Prompt",
  "custom.changes": "%d changes",
  "custom.dangerous.command": "Dangerous Command",
  "custom.sensitive.file": "Sensitive File",
  "custom.clear": "Clear",
  "custom.activity": "Activity",
  "custom.prompts": "Prompts",
  "custom.recent.file": "Recent file",
  "custom.changed.files": "Changed Files",
  "custom.last.commit": "Last Commit",
  "custom.commit.age": "Commit Age",
  "custom.na": "N/A",
  "custom.file.changes": "File Changes",
  "custom.no.tracked.file.changes": "No tracked file changes yet."
};

export function getLocale(preferred?: string): Locale {
  if (!preferred && forcedLocale) return forcedLocale;
  const browserLocale =
    typeof navigator !== "undefined" && typeof navigator.language === "string" ? navigator.language : "";
  const processLocale =
    typeof process !== "undefined" &&
    process?.env &&
    typeof process.env.LANG === "string"
      ? process.env.LANG
      : "";
  const value = String(preferred || browserLocale || processLocale).toLowerCase();
  if (value.startsWith("ko")) return "ko";
  return "en";
}

export function setPreferredLocale(preferred: string | null | undefined) {
  const value = String(preferred ?? "").toLowerCase();
  if (value.startsWith("ko")) {
    forcedLocale = "ko";
    return;
  }
  if (value.startsWith("en") || value.startsWith("ja")) {
    forcedLocale = "en";
    return;
  }
  forcedLocale = null;
}

export function t(key: string, preferred?: string): string {
  const locale = getLocale(preferred);
  return catalog[locale][key] ?? catalog.ko[key] ?? key;
}

export function tf(key: string, preferred: string | undefined, ...args: Array<string | number>): string {
  let template = t(key, preferred);
  for (const arg of args) {
    template = template.replace(/%@|%d/, String(arg));
  }
  return template;
}
