export type MacAchievementTier = 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';
export type MacCharacterSpecies = 'human' | 'cat' | 'dog' | 'rabbit' | 'bear' | 'penguin' | 'fox' | 'robot' | 'claude' | 'alien' | 'ghost' | 'dragon' | 'chicken' | 'owl' | 'frog' | 'panda' | 'unicorn' | 'skeleton';
export type MacWorkerJob = 'developer' | 'qa' | 'reporter' | 'boss' | 'planner' | 'reviewer' | 'designer' | 'sre';

export interface MacCharacterDefinition {
  id: string;
  name: string;
  archetype: string;
  hairColor: string;
  skinTone: string;
  shirtColor: string;
  pantsColor: string;
  hatType: string;
  accessory: string;
  species: MacCharacterSpecies;
  requiredAchievement: string | null;
  jobRole: MacWorkerJob;
  isHired: boolean;
}

export interface MacAchievementDefinition {
  id: string;
  icon: string;
  title: string;
  subtitle: string;
  xp: number;
  tier: MacAchievementTier;
}

export interface MacFurnitureDefinition {
  id: string;
  name: string;
  icon: string;
  width: number;
  height: number;
  isWallItem: boolean;
  requiredLevel: number | null;
  requiredAchievement: string | null;
}

export interface MacBackgroundDefinition {
  id: string;
  label: string;
  icon: string;
  requiredLevel: number | null;
}

export const macSpeciesMeta: Record<MacCharacterSpecies, { emoji: string; label: string }> = {
  human: { emoji: '👤', label: '인간' },
  cat: { emoji: '🐱', label: '고양이' },
  dog: { emoji: '🐶', label: '강아지' },
  rabbit: { emoji: '🐰', label: '토끼' },
  bear: { emoji: '🐻', label: '곰' },
  penguin: { emoji: '🐧', label: '펭귄' },
  fox: { emoji: '🦊', label: '여우' },
  robot: { emoji: '🤖', label: '로봇' },
  claude: { emoji: '✨', label: 'Claude' },
  alien: { emoji: '👽', label: '외계인' },
  ghost: { emoji: '👻', label: '유령' },
  dragon: { emoji: '🐉', label: '드래곤' },
  chicken: { emoji: '🐔', label: '닭' },
  owl: { emoji: '🦉', label: '부엉이' },
  frog: { emoji: '🐸', label: '개구리' },
  panda: { emoji: '🐼', label: '판다' },
  unicorn: { emoji: '🦄', label: '유니콘' },
  skeleton: { emoji: '💀', label: '해골' }
};

export const macJobMeta: Record<MacWorkerJob, { shortLabel: string; label: string; icon: string; tint: string }> = {
  developer: { shortLabel: 'DEV', label: '개발자', icon: '💻', tint: '#4c9dff' },
  qa: { shortLabel: 'QA', label: 'QA', icon: '🛡️', tint: '#4ed18a' },
  reporter: { shortLabel: 'MD', label: '보고서', icon: '📄', tint: '#b68cff' },
  boss: { shortLabel: 'CEO', label: '보스', icon: '👑', tint: '#f4b13d' },
  planner: { shortLabel: 'PM', label: '기획자', icon: '🗂️', tint: '#62d8f5' },
  reviewer: { shortLabel: 'REV', label: '리뷰어', icon: '✅', tint: '#f1c75b' },
  designer: { shortLabel: 'DES', label: '디자이너', icon: '🎨', tint: '#ef7fe4' },
  sre: { shortLabel: 'SRE', label: 'SRE', icon: '🖥️', tint: '#ff7a7a' }
};

export const macCharacterCatalog: MacCharacterDefinition[] = [
  { id: 'pixel', name: 'Pixel', archetype: '커피머신 ☕', hairColor: '4a3728', skinTone: 'ffd5b8', shirtColor: 'f08080', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: true },
  { id: 'byte', name: 'Byte', archetype: '야근 마스터', hairColor: '2c1810', skinTone: 'ffd5b8', shirtColor: '72d6a0', pantsColor: '3a4050', hatType: 'beanie', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: true },
  { id: 'code', name: 'Code', archetype: 'Ctrl+Z 중독자', hairColor: 'd4a574', skinTone: 'e8c4a0', shirtColor: 'f0c05a', pantsColor: '3a4050', hatType: 'none', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: true },
  { id: 'bug', name: 'Bug', archetype: '버그 제조기', hairColor: '8b4513', skinTone: 'ffd5b8', shirtColor: '78b4f0', pantsColor: '3a4050', hatType: 'cap', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: true },
  { id: 'chip', name: 'Chip', archetype: '슬랙 답장 안함', hairColor: '1a1a30', skinTone: 'c8a882', shirtColor: 'c490e8', pantsColor: '3a4050', hatType: 'none', accessory: 'sunglasses', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'kit', name: 'Kit', archetype: '코드 예술가', hairColor: 'e06060', skinTone: 'ffd5b8', shirtColor: 'f0a060', pantsColor: '3a4050', hatType: 'beret', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'dot', name: 'Dot', archetype: 'TODO 수집가', hairColor: '4040a0', skinTone: 'e8c4a0', shirtColor: '60d0c0', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'rex', name: 'Rex', archetype: '일단 머지', hairColor: 'c4a474', skinTone: 'ffd5b8', shirtColor: 'f080c0', pantsColor: '3a4050', hatType: 'headphones', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'nova', name: 'Nova', archetype: '조용한 천재', hairColor: 'e0e0ff', skinTone: 'ffd5b8', shirtColor: '8080f0', pantsColor: '2a3040', hatType: 'none', accessory: 'glasses', species: 'human', requiredAchievement: 'session_streak_7', jobRole: 'developer', isHired: false },
  { id: 'dash', name: 'Dash', archetype: '에너지 드링크', hairColor: 'ff6060', skinTone: 'e8c4a0', shirtColor: '40c0e0', pantsColor: '3a4050', hatType: 'cap', accessory: 'none', species: 'human', requiredAchievement: 'session_streak_3', jobRole: 'developer', isHired: false },
  { id: 'root', name: 'Root', archetype: '소리없는 강자', hairColor: '606060', skinTone: 'c8a882', shirtColor: '404040', pantsColor: '2a2a2a', hatType: 'none', accessory: 'sunglasses', species: 'human', requiredAchievement: 'centurion', jobRole: 'developer', isHired: false },
  { id: 'flux', name: 'Flux', archetype: '무한 리팩토링', hairColor: '50b050', skinTone: 'ffd5b8', shirtColor: 'e0e0e0', pantsColor: '3a4050', hatType: 'wizard', accessory: 'none', species: 'human', requiredAchievement: 'marathon', jobRole: 'developer', isHired: false },
  { id: 'sage', name: 'Sage', archetype: '회의실 점거범', hairColor: 'b0b0b0', skinTone: 'e8c4a0', shirtColor: '6080a0', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'human', requiredAchievement: 'complete_50', jobRole: 'developer', isHired: false },
  { id: 'bolt', name: 'Bolt', archetype: '핫픽스 장인', hairColor: 'f0c020', skinTone: 'ffd5b8', shirtColor: 'f0a020', pantsColor: '3a4050', hatType: 'hardhat', accessory: 'none', species: 'human', requiredAchievement: 'speed_demon', jobRole: 'developer', isHired: false },
  { id: 'pip', name: 'Pip', archetype: '의욕 만랩', hairColor: 'f0a060', skinTone: 'ffd5b8', shirtColor: '60a0f0', pantsColor: '4050a0', hatType: 'beanie', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'mochi', name: '모찌', archetype: '자리 이탈 중', hairColor: 'f0e0d0', skinTone: 'f5e6d0', shirtColor: 'f08080', pantsColor: '3a4050', hatType: 'none', accessory: 'none', species: 'cat', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'nabi', name: '나비', archetype: '키보드 위의 고양이', hairColor: '404040', skinTone: '505050', shirtColor: 'ffd369', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'cat', requiredAchievement: 'night_owl', jobRole: 'developer', isHired: false },
  { id: 'cheese', name: '치즈', archetype: '점심 2시간', hairColor: 'f0a030', skinTone: 'f0b040', shirtColor: '60c060', pantsColor: '3a4050', hatType: 'none', accessory: 'none', species: 'cat', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'bori', name: '보리', archetype: '런치 히어로', hairColor: 'c09060', skinTone: 'd0a070', shirtColor: '4090d0', pantsColor: '3a4050', hatType: 'cap', accessory: 'none', species: 'dog', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'coco', name: '코코', archetype: '배포 두려움', hairColor: 'f0f0f0', skinTone: 'f0e8e0', shirtColor: 'e06060', pantsColor: '3a4050', hatType: 'none', accessory: 'scarf', species: 'dog', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'ddu', name: '뚜', archetype: '새벽 커밋러', hairColor: 'f0e0e0', skinTone: 'f5e8e8', shirtColor: 'f090c0', pantsColor: '3a4050', hatType: 'none', accessory: 'none', species: 'rabbit', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'toki', name: '토키', archetype: '복붙 달인', hairColor: 'e0d0c0', skinTone: 'e8dcd0', shirtColor: '90c0f0', pantsColor: '3a4050', hatType: 'beanie', accessory: 'none', species: 'rabbit', requiredAchievement: 'bug_squasher', jobRole: 'developer', isHired: false },
  { id: 'gomi', name: '고미', archetype: '코딩하다 잠든 자', hairColor: '8b6040', skinTone: 'a07050', shirtColor: '40a060', pantsColor: '3a4050', hatType: 'hardhat', accessory: 'none', species: 'bear', requiredAchievement: 'ultra_marathon', jobRole: 'developer', isHired: false },
  { id: 'pengu', name: '펭구', archetype: '월급루팡', hairColor: '2a2a3a', skinTone: '3a3a4a', shirtColor: 'f0f0f0', pantsColor: '2a2a3a', hatType: 'none', accessory: 'sunglasses', species: 'penguin', requiredAchievement: 'token_whale', jobRole: 'developer', isHired: false },
  { id: 'yuri', name: '유리', archetype: '깃 충돌 유발자', hairColor: 'e07030', skinTone: 'e08040', shirtColor: 'f0c060', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'fox', requiredAchievement: 'git_master', jobRole: 'developer', isHired: false },
  { id: 'zero', name: 'Zero', archetype: 'Stack Overflow 의존', hairColor: '8090a0', skinTone: 'a0b0c0', shirtColor: '6080a0', pantsColor: '506070', hatType: 'none', accessory: 'none', species: 'robot', requiredAchievement: 'level_5', jobRole: 'developer', isHired: false },
  { id: 'ai01', name: 'AI-01', archetype: '주석 없는 자', hairColor: '60f0a0', skinTone: '90a0b0', shirtColor: '304050', pantsColor: '203040', hatType: 'headphones', accessory: 'none', species: 'robot', requiredAchievement: 'command_500', jobRole: 'developer', isHired: false },
  { id: 'claude_opus', name: 'Claude', archetype: 'Opus', hairColor: 'd97757', skinTone: 'f5e6d0', shirtColor: 'd97757', pantsColor: '2a2a3a', hatType: 'none', accessory: 'none', species: 'claude', requiredAchievement: null, jobRole: 'developer', isHired: true },
  { id: 'claude_sonnet', name: 'Sonnet', archetype: 'Sonnet', hairColor: '5b9cf6', skinTone: 'f5e6d0', shirtColor: '5b9cf6', pantsColor: '2a2a3a', hatType: 'none', accessory: 'none', species: 'claude', requiredAchievement: 'three_models', jobRole: 'developer', isHired: false },
  { id: 'claude_haiku', name: 'Haiku', archetype: 'Haiku', hairColor: '56d97e', skinTone: 'f5e6d0', shirtColor: '56d97e', pantsColor: '2a2a3a', hatType: 'none', accessory: 'none', species: 'claude', requiredAchievement: 'haiku_user', jobRole: 'developer', isHired: false },
  { id: 'zyx', name: 'Zyx', archetype: '차원 여행자', hairColor: '40f080', skinTone: '80f0a0', shirtColor: '206040', pantsColor: '103020', hatType: 'none', accessory: 'none', species: 'alien', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'nova_x', name: 'Nova-X', archetype: '텔레파시 코더', hairColor: 'a060ff', skinTone: 'c0a0f0', shirtColor: '6030a0', pantsColor: '301860', hatType: 'none', accessory: 'glasses', species: 'alien', requiredAchievement: 'token_whale', jobRole: 'developer', isHired: false },
  { id: 'blip', name: 'Blip', archetype: '0과 1의 존재', hairColor: '60f0f0', skinTone: '80e0e0', shirtColor: '206060', pantsColor: '104040', hatType: 'headphones', accessory: 'none', species: 'alien', requiredAchievement: 'level_8', jobRole: 'developer', isHired: false },
  { id: 'mars', name: 'Mars', archetype: '화성에서 온 PM', hairColor: 'f06040', skinTone: 'e0a080', shirtColor: 'c04020', pantsColor: '602010', hatType: 'none', accessory: 'sunglasses', species: 'alien', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'boo', name: 'Boo', archetype: '보이지 않는 버그', hairColor: 'd0d8e0', skinTone: 'e8ecf4', shirtColor: 'c0c8d8', pantsColor: 'a0a8b8', hatType: 'none', accessory: 'none', species: 'ghost', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'shade', name: 'Shade', archetype: '야간 배포 전문', hairColor: '8088a0', skinTone: 'b0b8d0', shirtColor: '606880', pantsColor: '404860', hatType: 'none', accessory: 'glasses', species: 'ghost', requiredAchievement: 'night_owl', jobRole: 'developer', isHired: false },
  { id: 'wisp', name: 'Wisp', archetype: '사라진 커밋', hairColor: 'a0e0ff', skinTone: 'd0f0ff', shirtColor: '80c0e0', pantsColor: '60a0c0', hatType: 'none', accessory: 'none', species: 'ghost', requiredAchievement: 'night_marathon', jobRole: 'developer', isHired: false },
  { id: 'drako', name: 'Drako', archetype: '서버 불지르는 자', hairColor: 'e04020', skinTone: 'c06040', shirtColor: 'a02010', pantsColor: '601008', hatType: 'none', accessory: 'none', species: 'dragon', requiredAchievement: 'error_10', jobRole: 'developer', isHired: false },
  { id: 'azure', name: 'Azure', archetype: '클라우드 날다', hairColor: '4090e0', skinTone: '80b0e0', shirtColor: '3070c0', pantsColor: '204080', hatType: 'none', accessory: 'none', species: 'dragon', requiredAchievement: 'cost_10', jobRole: 'developer', isHired: false },
  { id: 'ember', name: 'Ember', archetype: '핫픽스 화염구', hairColor: 'f0a030', skinTone: 'e0a060', shirtColor: 'd08020', pantsColor: 'a06010', hatType: 'crown', accessory: 'none', species: 'dragon', requiredAchievement: 'level_10', jobRole: 'developer', isHired: false },
  { id: 'kko', name: '꼬', archetype: '새벽 알람', hairColor: 'e0c080', skinTone: 'f0e0c0', shirtColor: 'f0f0e0', pantsColor: 'd0c0a0', hatType: 'none', accessory: 'none', species: 'chicken', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'dak', name: '닥', archetype: '치킨 타이머', hairColor: 'c0a060', skinTone: 'e0d0b0', shirtColor: 'd0a040', pantsColor: 'a08030', hatType: 'cap', accessory: 'none', species: 'chicken', requiredAchievement: 'early_bird', jobRole: 'developer', isHired: false },
  { id: 'hoot', name: 'Hoot', archetype: '코드 리뷰의 눈', hairColor: '8b6040', skinTone: 'a08060', shirtColor: '705030', pantsColor: '503820', hatType: 'none', accessory: 'glasses', species: 'owl', requiredAchievement: 'night_complete', jobRole: 'developer', isHired: false },
  { id: 'luna', name: 'Luna', archetype: '밤의 파수꾼', hairColor: '404060', skinTone: '606080', shirtColor: '303050', pantsColor: '202040', hatType: 'wizard', accessory: 'none', species: 'owl', requiredAchievement: 'night_marathon', jobRole: 'developer', isHired: false },
  { id: 'gae', name: '개굴', archetype: '점프 디버거', hairColor: '40a040', skinTone: '60c060', shirtColor: '308030', pantsColor: '206020', hatType: 'none', accessory: 'none', species: 'frog', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'ribbit', name: 'Ribbit', archetype: '워터폴 개발자', hairColor: '30b070', skinTone: '50d090', shirtColor: '208050', pantsColor: '106030', hatType: 'beanie', accessory: 'sunglasses', species: 'frog', requiredAchievement: 'focus_30', jobRole: 'developer', isHired: false },
  { id: 'bao', name: '바오', archetype: '대나무 먹방 중', hairColor: '202020', skinTone: 'f0f0f0', shirtColor: '1a1a1a', pantsColor: '101010', hatType: 'none', accessory: 'none', species: 'panda', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'mei', name: '메이', archetype: '느긋한 아키텍트', hairColor: '303030', skinTone: 'e8e8e8', shirtColor: 'f08080', pantsColor: '303030', hatType: 'none', accessory: 'glasses', species: 'panda', requiredAchievement: 'complete_25', jobRole: 'developer', isHired: false },
  { id: 'stella', name: 'Stella', archetype: '유니콘 스타트업', hairColor: 'ff80c0', skinTone: 'fff0f8', shirtColor: 'c060a0', pantsColor: '803868', hatType: 'crown', accessory: 'none', species: 'unicorn', requiredAchievement: 'level_5', jobRole: 'developer', isHired: false },
  { id: 'rainbow', name: 'Rainbow', archetype: '무지개 빌더', hairColor: 'f06080', skinTone: 'f8e8f0', shirtColor: '80a0f0', pantsColor: '5070c0', hatType: 'none', accessory: 'none', species: 'unicorn', requiredAchievement: 'complete_100', jobRole: 'developer', isHired: false },
  { id: 'bones', name: 'Bones', archetype: '레거시 코드', hairColor: 'e0e0e0', skinTone: 'f0f0e8', shirtColor: '404040', pantsColor: '2a2a2a', hatType: 'none', accessory: 'none', species: 'skeleton', requiredAchievement: 'centurion', jobRole: 'developer', isHired: false },
  { id: 'skull', name: 'Skull', archetype: '데드코드 수집가', hairColor: 'd0d0c8', skinTone: 'e8e8e0', shirtColor: '202020', pantsColor: '101010', hatType: 'headphones', accessory: 'sunglasses', species: 'skeleton', requiredAchievement: 'command_1000', jobRole: 'developer', isHired: false },
  { id: 'ace', name: 'Ace', archetype: 'PR 무시맨', hairColor: '303040', skinTone: 'c8a882', shirtColor: 'e04040', pantsColor: '3a4050', hatType: 'cap', accessory: 'none', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'ivy', name: 'Ivy', archetype: '테스트 뭐하는거?', hairColor: '205020', skinTone: 'ffd5b8', shirtColor: '40a060', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'max', name: 'Max', archetype: '에러 친구', hairColor: 'a08040', skinTone: 'e8c4a0', shirtColor: 'd06030', pantsColor: '3a4050', hatType: 'hardhat', accessory: 'none', species: 'human', requiredAchievement: 'error_5', jobRole: 'developer', isHired: false },
  { id: 'sky', name: 'Sky', archetype: '배포 두려움 극복', hairColor: '80b0e0', skinTone: 'ffd5b8', shirtColor: '4080c0', pantsColor: '3a4050', hatType: 'none', accessory: 'none', species: 'human', requiredAchievement: 'complete_10', jobRole: 'developer', isHired: false },
  { id: 'zen', name: 'Zen', archetype: '롤백 전문가', hairColor: '808080', skinTone: 'e8c4a0', shirtColor: 'b0b0b0', pantsColor: '3a4050', hatType: 'none', accessory: 'glasses', species: 'human', requiredAchievement: 'marathon', jobRole: 'developer', isHired: false },
  { id: 'bit', name: 'Bit', archetype: '바이너리 토커', hairColor: '50e050', skinTone: '80a090', shirtColor: '206030', pantsColor: '103020', hatType: 'none', accessory: 'none', species: 'robot', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'cpu', name: 'CPU', archetype: '오버클럭 중', hairColor: 'f06060', skinTone: 'a0b0c0', shirtColor: '804040', pantsColor: '503030', hatType: 'headphones', accessory: 'none', species: 'robot', requiredAchievement: 'speed_2min', jobRole: 'developer', isHired: false },
  { id: 'tuna', name: '참치', archetype: '간식 협상가', hairColor: '808080', skinTone: 'a0a0a0', shirtColor: '5080a0', pantsColor: '3a4050', hatType: 'none', accessory: 'none', species: 'cat', requiredAchievement: 'lunch_coder', jobRole: 'developer', isHired: false },
  { id: 'maru', name: '마루', archetype: '꼬리 흔드는 QA', hairColor: 'e0c080', skinTone: 'f0d8b0', shirtColor: 'e08040', pantsColor: '3a4050', hatType: 'none', accessory: 'scarf', species: 'dog', requiredAchievement: 'complete_5', jobRole: 'developer', isHired: false },
  { id: 'nebula', name: 'Nebula', archetype: '우주 디버거', hairColor: '8040c0', skinTone: 'a070e0', shirtColor: '5020a0', pantsColor: '301060', hatType: 'none', accessory: 'glasses', species: 'alien', requiredAchievement: 'token_10k_total', jobRole: 'developer', isHired: false },
  { id: 'phantom', name: 'Phantom', archetype: '404 Not Found', hairColor: '6070a0', skinTone: '90a0c0', shirtColor: '4050a0', pantsColor: '303080', hatType: 'none', accessory: 'mask', species: 'ghost', requiredAchievement: 'complete_50', jobRole: 'developer', isHired: false },
  { id: 'frost', name: 'Frost', archetype: '서버 냉각기', hairColor: '80c0f0', skinTone: 'a0d0f0', shirtColor: '4080c0', pantsColor: '205080', hatType: 'crown', accessory: 'none', species: 'dragon', requiredAchievement: 'session_streak_7', jobRole: 'developer', isHired: false },
  { id: 'egg', name: '알', archetype: '', hairColor: 'f0e8d0', skinTone: 'f8f0e0', shirtColor: 'f0e0c0', pantsColor: 'e0d0b0', hatType: 'none', accessory: 'none', species: 'chicken', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'wise', name: 'Wise', archetype: '시니어 코드 리뷰어', hairColor: 'c0b0a0', skinTone: 'd0c0b0', shirtColor: '605040', pantsColor: '403020', hatType: 'wizard', accessory: 'glasses', species: 'owl', requiredAchievement: 'git_master_25', jobRole: 'developer', isHired: false },
  { id: 'lily', name: 'Lily', archetype: '연잎 위의 리모트워커', hairColor: '30c050', skinTone: '50e070', shirtColor: 'f0a0c0', pantsColor: 'c07090', hatType: 'beret', accessory: 'none', species: 'frog', requiredAchievement: 'weekend_warrior', jobRole: 'developer', isHired: false },
  { id: 'yin', name: 'Yin', archetype: '야근조', hairColor: '1a1a1a', skinTone: 'f0f0f0', shirtColor: '303030', pantsColor: '1a1a1a', hatType: 'headphones', accessory: 'none', species: 'panda', requiredAchievement: 'night_owl', jobRole: 'developer', isHired: false },
  { id: 'prism', name: 'Prism', archetype: '프리즘 리팩토러', hairColor: '40d0f0', skinTone: 'f0f0ff', shirtColor: 'f080f0', pantsColor: 'a050a0', hatType: 'none', accessory: 'sunglasses', species: 'unicorn', requiredAchievement: 'three_models', jobRole: 'developer', isHired: false },
  { id: 'grim', name: 'Grim', archetype: 'rm -rf /', hairColor: 'c0c0b0', skinTone: 'e0e0d8', shirtColor: '101010', pantsColor: '080808', hatType: 'none', accessory: 'none', species: 'skeleton', requiredAchievement: 'command_5000', jobRole: 'developer', isHired: false },
  { id: 'snow', name: 'Snow', archetype: '화이트박스 테스터', hairColor: 'f0f0f0', skinTone: 'f8f0f0', shirtColor: 'f0c0d0', pantsColor: 'd0a0b0', hatType: 'none', accessory: 'none', species: 'rabbit', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'choco', name: 'Choco', archetype: '초콜릿 빌더', hairColor: '6a4030', skinTone: '8b6040', shirtColor: 'c08060', pantsColor: '805040', hatType: 'beanie', accessory: 'none', species: 'rabbit', requiredAchievement: 'session_10', jobRole: 'developer', isHired: false },
  { id: 'polar', name: 'Polar', archetype: '북극곰 SRE', hairColor: 'e8e8f0', skinTone: 'f0f0f8', shirtColor: '80a0c0', pantsColor: '506080', hatType: 'none', accessory: 'scarf', species: 'bear', requiredAchievement: 'snow', jobRole: 'developer', isHired: false },
  { id: 'tux', name: 'Tux', archetype: '리눅스 커널 해커', hairColor: '1a1a2a', skinTone: '2a2a3a', shirtColor: 'f8f8f8', pantsColor: '1a1a2a', hatType: 'headphones', accessory: 'none', species: 'penguin', requiredAchievement: 'opus_user', jobRole: 'developer', isHired: false },
  { id: 'firefox', name: 'Firefox', archetype: '브라우저 전쟁 생존자', hairColor: 'f04020', skinTone: 'f06030', shirtColor: 'e08020', pantsColor: 'a05010', hatType: 'none', accessory: 'sunglasses', species: 'fox', requiredAchievement: 'speed_demon', jobRole: 'developer', isHired: false },
  { id: 'luna_h', name: '루나', archetype: '달빛 코더', hairColor: 'c0b8d0', skinTone: 'ffd5b8', shirtColor: '6060a0', pantsColor: '3a3a60', hatType: 'none', accessory: 'earring', species: 'human', requiredAchievement: 'night_complete', jobRole: 'developer', isHired: false },
  { id: 'sol', name: 'Sol', archetype: '일출 배포', hairColor: 'f0c040', skinTone: 'e8c4a0', shirtColor: 'f08030', pantsColor: 'a05020', hatType: 'cap', accessory: 'none', species: 'human', requiredAchievement: 'morning_complete', jobRole: 'developer', isHired: false },
  { id: 'storm_h', name: 'Storm', archetype: '핫픽스 폭풍', hairColor: '404060', skinTone: 'ffd5b8', shirtColor: '3050a0', pantsColor: '202848', hatType: 'none', accessory: 'none', species: 'human', requiredAchievement: 'speed_2min', jobRole: 'developer', isHired: false },
  { id: 'jade', name: 'Jade', archetype: '그린필드 개척자', hairColor: '1a3020', skinTone: 'c8a882', shirtColor: '40a060', pantsColor: '205030', hatType: 'hardhat', accessory: 'glasses', species: 'human', requiredAchievement: null, jobRole: 'developer', isHired: false },
  { id: 'ruby', name: 'Ruby', archetype: '레드팀 리더', hairColor: 'a02020', skinTone: 'ffd5b8', shirtColor: 'c03030', pantsColor: '801818', hatType: 'none', accessory: 'none', species: 'human', requiredAchievement: 'error_10', jobRole: 'developer', isHired: false },
  { id: 'indigo', name: 'Indigo', archetype: '딥워크 마스터', hairColor: '3030a0', skinTone: 'e8c4a0', shirtColor: '4040c0', pantsColor: '2a2a80', hatType: 'beret', accessory: 'glasses', species: 'human', requiredAchievement: 'ultra_marathon', jobRole: 'developer', isHired: false },
  { id: 'secret_tracker', name: '히든 트래커', archetype: '숨겨진 프로젝트 정찰병', hairColor: '5c6bc0', skinTone: 'd8d8ff', shirtColor: '6fa8ff', pantsColor: '33445f', hatType: 'none', accessory: 'glasses', species: 'ghost', requiredAchievement: 'session_50', jobRole: 'planner', isHired: false },
  { id: 'secret_market', name: '히든 마켓', archetype: '플러그인 마켓 암상인', hairColor: '8e44ad', skinTone: 'f4d7ff', shirtColor: '9b59b6', pantsColor: '4b2b63', hatType: 'wizard', accessory: 'mask', species: 'owl', requiredAchievement: 'three_models', jobRole: 'designer', isHired: false },
  { id: 'secret_debug', name: '히든 디버그', archetype: '새벽 버그 수호령', hairColor: '9aa7b0', skinTone: 'dfe7ef', shirtColor: '4fc3f7', pantsColor: '2c3e50', hatType: 'headphones', accessory: 'none', species: 'robot', requiredAchievement: 'night_marathon', jobRole: 'reviewer', isHired: false }
];

export const macAchievementCatalog: MacAchievementDefinition[] = [
  { id: 'first_session', icon: '🎬', title: '첫 걸음', subtitle: '첫 번째 세션을 시작했다', xp: 30, tier: 'common' },
  { id: 'first_complete', icon: '✅', title: '완료!', subtitle: '첫 번째 작업을 완료했다', xp: 30, tier: 'common' },
  { id: 'first_bash', icon: '💻', title: '첫 명령어', subtitle: '첫 Bash 명령을 실행했다', xp: 20, tier: 'common' },
  { id: 'first_edit', icon: '✏️', title: '첫 수정', subtitle: '첫 번째 파일을 수정했다', xp: 20, tier: 'common' },
  { id: 'command_10', icon: '🔟', title: '열 번의 손짓', subtitle: '명령을 10번 실행했다', xp: 25, tier: 'common' },
  { id: 'complete_5', icon: '🖐', title: '다섯 번째 성공', subtitle: '작업을 5번 완료했다', xp: 30, tier: 'common' },
  { id: 'complete_10', icon: '🔄', title: '열 번째 성공', subtitle: '작업을 10번 완료했다', xp: 35, tier: 'common' },
  { id: 'session_10', icon: '📋', title: '열 번째 출근', subtitle: '세션을 10번 시작했다', xp: 30, tier: 'common' },
  { id: 'token_first_1k', icon: '🪙', title: '첫 천 토큰', subtitle: '누적 1,000 토큰을 사용했다', xp: 25, tier: 'common' },
  { id: 'weekend_warrior', icon: '🎮', title: '주말 전사', subtitle: '주말에 작업했다', xp: 30, tier: 'common' },
  { id: 'read_10', icon: '📖', title: '독서가', subtitle: '한 세션에서 파일을 10번 읽었다', xp: 25, tier: 'common' },
  { id: 'cost_first', icon: '💵', title: '첫 지출', subtitle: 'API 비용이 발생했다', xp: 20, tier: 'common' },
  { id: 'five_sessions', icon: '🖐🏻', title: '다섯 손가락', subtitle: '5개 세션을 동시에 실행했다', xp: 40, tier: 'common' },
  { id: 'file_edit_5', icon: '📝', title: '다섯 줄 수정', subtitle: '파일을 5번 수정했다', xp: 25, tier: 'common' },
  { id: 'monday_blues', icon: '😩', title: '월요병', subtitle: '월요일에 작업했다', xp: 25, tier: 'common' },
  { id: 'friday_coder', icon: '🎉', title: '불금 코더', subtitle: '금요일에 작업했다', xp: 25, tier: 'common' },
  { id: 'night_owl', icon: '🦉', title: '야행성', subtitle: '자정~새벽 5시 사이에 작업했다', xp: 50, tier: 'rare' },
  { id: 'early_bird', icon: '🐦', title: '얼리버드', subtitle: '새벽 4~6시 사이에 작업했다', xp: 50, tier: 'rare' },
  { id: 'speed_demon', icon: '⚡', title: '스피드 데몬', subtitle: '5분 안에 작업을 완료했다', xp: 50, tier: 'rare' },
  { id: 'multi_tasker', icon: '🤹', title: '멀티태스커', subtitle: '3개 이상 동시에 작업했다', xp: 50, tier: 'rare' },
  { id: 'pair_programmer', icon: '👯', title: '페어 프로그래머', subtitle: '같은 프로젝트에 2명을 배정했다', xp: 50, tier: 'rare' },
  { id: 'bug_squasher', icon: '🪲', title: '벌레 사냥꾼', subtitle: '에러 상태에서 복구했다', xp: 50, tier: 'rare' },
  { id: 'token_saver', icon: '💰', title: '절약왕', subtitle: '1k 토큰 이하로 작업을 완료했다', xp: 50, tier: 'rare' },
  { id: 'command_50', icon: '5️⃣', title: '반백', subtitle: '명령을 50번 실행했다', xp: 45, tier: 'rare' },
  { id: 'complete_25', icon: '🎖', title: '숙련공', subtitle: '작업을 25번 완료했다', xp: 50, tier: 'rare' },
  { id: 'session_25', icon: '📊', title: '출근왕', subtitle: '세션을 25번 시작했다', xp: 45, tier: 'rare' },
  { id: 'lunch_coder', icon: '🍱', title: '점심시간 코더', subtitle: '점심시간(12~13시)에 작업했다', xp: 40, tier: 'rare' },
  { id: 'file_surgeon', icon: '🔪', title: '외과의사', subtitle: '한 세션에서 5개 이상 파일을 수정했다', xp: 50, tier: 'rare' },
  { id: 'cost_1', icon: '💲', title: '첫 달러', subtitle: '누적 비용 $1을 넘었다', xp: 50, tier: 'rare' },
  { id: 'focus_30', icon: '🧘', title: '집중력', subtitle: '30분 이상 연속 작업했다', xp: 45, tier: 'rare' },
  { id: 'error_5', icon: '💪', title: '불굴의 의지', subtitle: '에러에서 5번 복구했다', xp: 55, tier: 'rare' },
  { id: 'opus_user', icon: '🟣', title: '오퍼스 유저', subtitle: 'Opus 모델을 사용했다', xp: 40, tier: 'rare' },
  { id: 'haiku_user', icon: '🟢', title: '하이쿠 유저', subtitle: 'Haiku 모델을 사용했다', xp: 40, tier: 'rare' },
  { id: 'token_10k_total', icon: '📈', title: '만 토큰 클럽', subtitle: '누적 10,000 토큰을 사용했다', xp: 50, tier: 'rare' },
  { id: 'git_first_branch', icon: '🌱', title: '가지치기', subtitle: 'Git 브랜치에서 작업했다', xp: 35, tier: 'rare' },
  { id: 'session_streak_3', icon: '🔥', title: '3일 연속', subtitle: '3일 연속으로 작업했다', xp: 55, tier: 'rare' },
  { id: 'night_complete', icon: '🌙', title: '달빛 코더', subtitle: '밤 10시 이후에 작업을 완료했다', xp: 40, tier: 'rare' },
  { id: 'morning_complete', icon: '🌅', title: '아침형 인간', subtitle: '오전 9시 전에 작업을 완료했다', xp: 40, tier: 'rare' },
  { id: 'file_edit_25', icon: '🗂', title: '정리의 달인', subtitle: '파일을 25번 수정했다', xp: 45, tier: 'rare' },
  { id: 'file_edit_50', icon: '📚', title: '리팩토링 장인', subtitle: '파일을 50번 수정했다', xp: 55, tier: 'rare' },
  { id: 'cost_5', icon: '💳', title: '구독자', subtitle: '누적 비용 $5를 넘었다', xp: 45, tier: 'rare' },
  { id: 'read_50', icon: '🔍', title: '탐정', subtitle: '파일을 50번 읽었다', xp: 45, tier: 'rare' },
  { id: 'dawn_warrior', icon: '🌄', title: '새벽 전사', subtitle: '새벽 3시에 작업 중이었다', xp: 55, tier: 'rare' },
  { id: 'token_5k_session', icon: '📊', title: '알찬 세션', subtitle: '한 세션에서 5k 이상 토큰을 사용했다', xp: 45, tier: 'rare' },
  { id: 'marathon', icon: '🏃', title: '마라톤', subtitle: '1시간 이상 연속으로 작업했다', xp: 80, tier: 'epic' },
  { id: 'git_master', icon: '🌿', title: 'Git 마스터', subtitle: '한 세션에서 10개 이상 파일을 변경했다', xp: 80, tier: 'epic' },
  { id: 'centurion', icon: '💯', title: '백전노장', subtitle: '명령을 100번 실행했다', xp: 80, tier: 'epic' },
  { id: 'token_whale', icon: '🐋', title: '토큰 고래', subtitle: '한 세션에서 10k 이상 토큰을 사용했다', xp: 80, tier: 'epic' },
  { id: 'complete_50', icon: '🏅', title: '베테랑', subtitle: '작업을 50번 완료했다', xp: 80, tier: 'epic' },
  { id: 'complete_100', icon: '🎯', title: '백전백승', subtitle: '작업을 100번 완료했다', xp: 100, tier: 'epic' },
  { id: 'command_500', icon: '⚔️', title: '오백장군', subtitle: '명령을 500번 실행했다', xp: 90, tier: 'epic' },
  { id: 'session_50', icon: '🏢', title: '근속상', subtitle: '세션을 50번 시작했다', xp: 80, tier: 'epic' },
  { id: 'ultra_marathon', icon: '🏔', title: '울트라 마라톤', subtitle: '3시간 이상 연속으로 작업했다', xp: 100, tier: 'epic' },
  { id: 'cost_10', icon: '💎', title: '큰손', subtitle: '누적 비용 $10을 넘었다', xp: 90, tier: 'epic' },
  { id: 'token_100k_total', icon: '🏦', title: '토큰 부자', subtitle: '누적 100,000 토큰을 사용했다', xp: 90, tier: 'epic' },
  { id: 'git_master_25', icon: '🌳', title: 'Git 장인', subtitle: '한 세션에서 25개 이상 파일을 변경했다', xp: 90, tier: 'epic' },
  { id: 'multi_5', icon: '🎪', title: '오케스트라 지휘자', subtitle: '5개 이상 동시에 작업했다', xp: 85, tier: 'epic' },
  { id: 'error_10', icon: '🔥', title: '불사조', subtitle: '에러에서 10번 복구했다', xp: 85, tier: 'epic' },
  { id: 'speed_2min', icon: '🚀', title: '번개', subtitle: '2분 안에 작업을 완료했다', xp: 85, tier: 'epic' },
  { id: 'night_marathon', icon: '🌃', title: '야간 마라톤', subtitle: '자정~5시에 1시간 이상 작업했다', xp: 95, tier: 'epic' },
  { id: 'three_models', icon: '🎨', title: '삼총사', subtitle: '세 가지 모델을 모두 사용했다', xp: 80, tier: 'epic' },
  { id: 'session_streak_7', icon: '📆', title: '7일 연속', subtitle: '7일 연속으로 작업했다', xp: 100, tier: 'epic' },
  { id: 'token_50k_session', icon: '🐳', title: '메가 세션', subtitle: '한 세션에서 50k 이상 토큰을 사용했다', xp: 90, tier: 'epic' },
  { id: 'git_branch_5', icon: '🌲', title: '브랜치 달인', subtitle: '5개 이상 다른 브랜치에서 작업했다', xp: 80, tier: 'epic' },
  { id: 'file_surgeon_10', icon: '⚕️', title: '집도의', subtitle: '한 세션에서 10개 이상 파일을 수정했다', xp: 85, tier: 'epic' },
  { id: 'complete_200', icon: '🎗', title: '프로', subtitle: '작업을 200번 완료했다', xp: 90, tier: 'epic' },
  { id: 'file_edit_100', icon: '🏗', title: '건축가', subtitle: '파일을 100번 수정했다', xp: 85, tier: 'epic' },
  { id: 'read_200', icon: '📚', title: '학자', subtitle: '파일을 200번 읽었다', xp: 80, tier: 'epic' },
  { id: 'error_25', icon: '🛡', title: '방패', subtitle: '에러에서 25번 복구했다', xp: 95, tier: 'epic' },
  { id: 'cost_50', icon: '💰', title: '투자자', subtitle: '누적 비용 $50을 넘었다', xp: 95, tier: 'epic' },
  { id: 'session_streak_14', icon: '🗓', title: '2주 연속', subtitle: '14일 연속으로 작업했다', xp: 100, tier: 'epic' },
  { id: 'git_branch_10', icon: '🌴', title: '숲의 관리자', subtitle: '10개 이상 다른 브랜치에서 작업했다', xp: 90, tier: 'epic' },
  { id: 'token_500k_total', icon: '🏧', title: '토큰 재벌', subtitle: '누적 500,000 토큰을 사용했다', xp: 95, tier: 'epic' },
  { id: 'speed_1min', icon: '💨', title: '섬광', subtitle: '1분 안에 작업을 완료했다', xp: 100, tier: 'epic' },
  { id: 'marathon_6h', icon: '🏕', title: '캠프파이어', subtitle: '6시간 이상 연속으로 작업했다', xp: 110, tier: 'epic' },
  { id: 'token_100k_session', icon: '🦈', title: '메갈로돈', subtitle: '한 세션에서 100k 이상 토큰을 사용했다', xp: 100, tier: 'epic' },
  { id: 'git_master_50', icon: '🏔', title: '산을 옮기다', subtitle: '한 세션에서 50개 이상 파일을 변경했다', xp: 100, tier: 'epic' },
  { id: 'session_75', icon: '🎓', title: '졸업', subtitle: '세션을 75번 시작했다', xp: 90, tier: 'epic' },
  { id: 'read_500', icon: '🧠', title: '브레인', subtitle: '파일을 500번 읽었다', xp: 90, tier: 'epic' },
  { id: 'file_edit_200', icon: '⚒', title: '대장장이', subtitle: '파일을 200번 수정했다', xp: 90, tier: 'epic' },
  { id: 'complete_300', icon: '🗻', title: '등산가', subtitle: '작업을 300번 완료했다', xp: 95, tier: 'epic' },
  { id: 'night_owl_10', icon: '🦇', title: '박쥐', subtitle: '심야 작업을 10일 이상 했다', xp: 95, tier: 'epic' },
  { id: 'level_5', icon: '⭐', title: '스타 개발자', subtitle: '레벨 5에 도달했다', xp: 150, tier: 'legendary' },
  { id: 'level_8', icon: '🏆', title: '전설의 시작', subtitle: '레벨 8에 도달했다', xp: 200, tier: 'legendary' },
  { id: 'level_10', icon: '🌌', title: '우주의 끝', subtitle: '레벨 10에 도달했다', xp: 300, tier: 'legendary' },
  { id: 'complete_500', icon: '👑', title: '천하무적', subtitle: '작업을 500번 완료했다', xp: 250, tier: 'legendary' },
  { id: 'command_1000', icon: '🗡', title: '천 번의 손짓', subtitle: '명령을 1,000번 실행했다', xp: 200, tier: 'legendary' },
  { id: 'command_5000', icon: '⚜️', title: '만능 해커', subtitle: '명령을 5,000번 실행했다', xp: 300, tier: 'legendary' },
  { id: 'session_100', icon: '🏛', title: '출퇴근 달인', subtitle: '세션을 100번 시작했다', xp: 200, tier: 'legendary' },
  { id: 'token_million', icon: '💫', title: '백만장자', subtitle: '누적 1,000,000 토큰을 사용했다', xp: 250, tier: 'legendary' },
  { id: 'cost_100', icon: '🤑', title: '큰 후원자', subtitle: '누적 비용 $100을 넘었다', xp: 200, tier: 'legendary' },
  { id: 'session_streak_30', icon: '🔱', title: '30일 연속', subtitle: '30일 연속으로 작업했다', xp: 300, tier: 'legendary' },
  { id: 'perfectionist', icon: '🎆', title: '완벽주의자', subtitle: '전설 등급 외 모든 업적을 달성했다', xp: 500, tier: 'legendary' },
  { id: 'complete_1000', icon: '🐉', title: '용', subtitle: '작업을 1,000번 완료했다', xp: 400, tier: 'legendary' },
  { id: 'command_10000', icon: '🌠', title: '별을 헤아리며', subtitle: '명령을 10,000번 실행했다', xp: 350, tier: 'legendary' },
  { id: 'file_edit_500', icon: '🗿', title: '불멸의 조각가', subtitle: '파일을 500번 수정했다', xp: 300, tier: 'legendary' },
  { id: 'error_50', icon: '🔮', title: '예언자', subtitle: '에러에서 50번 복구했다', xp: 250, tier: 'legendary' },
  { id: 'session_streak_100', icon: '💎', title: '다이아몬드', subtitle: '100일 연속으로 작업했다', xp: 500, tier: 'legendary' },
  { id: 'session_500', icon: '🏰', title: '성을 쌓다', subtitle: '세션을 500번 시작했다', xp: 350, tier: 'legendary' },
  { id: 'cost_500', icon: '🏦', title: '은행장', subtitle: '누적 비용 $500을 넘었다', xp: 350, tier: 'legendary' },
  { id: 'token_5million', icon: '🪐', title: '행성', subtitle: '누적 5,000,000 토큰을 사용했다', xp: 400, tier: 'legendary' },
  { id: 'complete_2000', icon: '☀️', title: '태양', subtitle: '작업을 2,000번 완료했다', xp: 500, tier: 'legendary' },
  { id: 'session_streak_365', icon: '♾️', title: '무한', subtitle: '365일 연속으로 작업했다', xp: 1000, tier: 'legendary' },
  { id: 'command_50000', icon: '🔨', title: '광부', subtitle: '명령을 50,000번 실행했다', xp: 500, tier: 'legendary' },
  { id: 'level_15', icon: '🌟', title: '별 중의 별', subtitle: '레벨 15에 도달했다', xp: 400, tier: 'legendary' },
  { id: 'level_20', icon: '💠', title: '다이아몬드 코어', subtitle: '레벨 20에 도달했다', xp: 500, tier: 'legendary' },
  { id: 'complete_3000', icon: '🏹', title: '만발의 궁수', subtitle: '작업을 3,000번 완료했다', xp: 500, tier: 'legendary' },
  { id: 'command_20000', icon: '⛏️', title: '채굴왕', subtitle: '명령을 20,000번 실행했다', xp: 400, tier: 'legendary' },
  { id: 'session_2000', icon: '🏙', title: '도시를 세우다', subtitle: '세션을 2,000번 시작했다', xp: 450, tier: 'legendary' },
  { id: 'token_10million', icon: '🌍', title: '지구', subtitle: '누적 10,000,000 토큰을 사용했다', xp: 500, tier: 'legendary' },
  { id: 'cost_1000', icon: '🏦', title: '재벌', subtitle: '누적 비용 $1,000을 넘었다', xp: 500, tier: 'legendary' },
  { id: 'file_edit_1000', icon: '🏗️', title: '마천루', subtitle: '파일을 1,000번 수정했다', xp: 400, tier: 'legendary' },
  { id: 'read_1000', icon: '🔬', title: '연구원', subtitle: '파일을 1,000번 읽었다', xp: 350, tier: 'legendary' },
  { id: 'read_2000', icon: '🧬', title: '게놈 해독자', subtitle: '파일을 2,000번 읽었다', xp: 400, tier: 'legendary' },
  { id: 'error_100', icon: '🧱', title: '만리장성', subtitle: '에러에서 100번 복구했다', xp: 400, tier: 'legendary' },
  { id: 'git_branch_30', icon: '🌲', title: '고목나무', subtitle: '30개 이상 다른 브랜치에서 작업했다', xp: 350, tier: 'legendary' },
  { id: 'git_branch_50', icon: '🏞', title: '밀림 탐험가', subtitle: '50개 이상 다른 브랜치에서 작업했다', xp: 400, tier: 'legendary' },
  { id: 'night_owl_50', icon: '🌑', title: '암흑의 제왕', subtitle: '심야 작업을 50일 이상 했다', xp: 400, tier: 'legendary' },
  { id: 'session_streak_60', icon: '📿', title: '60일 연속', subtitle: '60일 연속으로 작업했다', xp: 450, tier: 'legendary' },
  { id: 'session_streak_180', icon: '🧭', title: '반년의 여정', subtitle: '180일 연속으로 작업했다', xp: 600, tier: 'legendary' },
  { id: 'marathon_12h', icon: '🏜', title: '사막 횡단', subtitle: '12시간 이상 연속으로 작업했다', xp: 500, tier: 'legendary' },
  { id: 'weekend_50', icon: '🎪', title: '주말의 지배자', subtitle: '주말에 50일 이상 작업했다', xp: 400, tier: 'legendary' },
  { id: 'multi_7', icon: '🎰', title: '럭키 세븐', subtitle: '7개 이상 동시에 작업했다', xp: 400, tier: 'legendary' },
  { id: 'git_master_100', icon: '🌋', title: '화산 폭발', subtitle: '한 세션에서 100개 이상 파일을 변경했다', xp: 450, tier: 'legendary' },
  { id: 'token_200k_session', icon: '🐘', title: '매머드', subtitle: '한 세션에서 200k 이상 토큰을 사용했다', xp: 450, tier: 'legendary' },
  { id: 'file_surgeon_25', icon: '🏥', title: '종합병원', subtitle: '한 세션에서 25개 이상 파일을 수정했다', xp: 400, tier: 'legendary' },
  { id: 'complete_5000', icon: '🐲', title: '용왕', subtitle: '작업을 5,000번 완료했다', xp: 800, tier: 'mythic' },
  { id: 'complete_10000', icon: '🕳️', title: '블랙홀', subtitle: '작업을 10,000번 완료했다', xp: 1500, tier: 'mythic' },
  { id: 'command_100000', icon: '🌌', title: '은하수', subtitle: '명령을 100,000번 실행했다', xp: 1000, tier: 'mythic' },
  { id: 'command_500000', icon: '🔭', title: '관측 가능한 우주', subtitle: '명령을 500,000번 실행했다', xp: 2000, tier: 'mythic' },
  { id: 'session_5000', icon: '🌐', title: '글로벌 네트워크', subtitle: '세션을 5,000번 시작했다', xp: 800, tier: 'mythic' },
  { id: 'session_10000', icon: '🪐', title: '항성계', subtitle: '세션을 10,000번 시작했다', xp: 1500, tier: 'mythic' },
  { id: 'token_50million', icon: '🌞', title: '항성', subtitle: '누적 50,000,000 토큰을 사용했다', xp: 1000, tier: 'mythic' },
  { id: 'token_100million', icon: '💥', title: '빅뱅', subtitle: '누적 100,000,000 토큰을 사용했다', xp: 1500, tier: 'mythic' },
  { id: 'token_1billion', icon: '🔮', title: '오메가 포인트', subtitle: '누적 1,000,000,000 토큰을 사용했다', xp: 3000, tier: 'mythic' },
  { id: 'token_500k_session', icon: '🦕', title: '브론토사우루스', subtitle: '한 세션에서 500k 이상 토큰을 사용했다', xp: 800, tier: 'mythic' },
  { id: 'token_1m_session', icon: '☄️', title: '혜성 충돌', subtitle: '한 세션에서 1M 이상 토큰을 사용했다', xp: 1200, tier: 'mythic' },
  { id: 'cost_5000', icon: '👸', title: '여왕', subtitle: '누적 비용 $5,000을 넘었다', xp: 1000, tier: 'mythic' },
  { id: 'cost_10000', icon: '🤴', title: '황제', subtitle: '누적 비용 $10,000을 넘었다', xp: 1500, tier: 'mythic' },
  { id: 'cost_50000', icon: '🏛️', title: '연방 예산', subtitle: '누적 비용 $50,000을 넘었다', xp: 3000, tier: 'mythic' },
  { id: 'file_edit_2000', icon: '⚙️', title: '기계 심장', subtitle: '파일을 2,000번 수정했다', xp: 700, tier: 'mythic' },
  { id: 'file_edit_5000', icon: '🧬', title: '진화', subtitle: '파일을 5,000번 수정했다', xp: 1000, tier: 'mythic' },
  { id: 'file_edit_10000', icon: '🌊', title: '쓰나미', subtitle: '파일을 10,000번 수정했다', xp: 1500, tier: 'mythic' },
  { id: 'file_edit_50000', icon: '🏔️', title: '에베레스트', subtitle: '파일을 50,000번 수정했다', xp: 3000, tier: 'mythic' },
  { id: 'read_5000', icon: '📡', title: '위성 수신', subtitle: '파일을 5,000번 읽었다', xp: 800, tier: 'mythic' },
  { id: 'read_10000', icon: '🛸', title: '외계 통신', subtitle: '파일을 10,000번 읽었다', xp: 1200, tier: 'mythic' },
  { id: 'read_50000', icon: '🧠', title: '초지능', subtitle: '파일을 50,000번 읽었다', xp: 2000, tier: 'mythic' },
  { id: 'error_200', icon: '🦾', title: '사이보그', subtitle: '에러에서 200번 복구했다', xp: 800, tier: 'mythic' },
  { id: 'error_500', icon: '🤖', title: '터미네이터', subtitle: '에러에서 500번 복구했다', xp: 1500, tier: 'mythic' },
  { id: 'error_1000', icon: '🛡️', title: '절대 방패', subtitle: '에러에서 1,000번 복구했다', xp: 2500, tier: 'mythic' },
  { id: 'git_branch_100', icon: '🌳', title: '세계수', subtitle: '100개 이상 다른 브랜치에서 작업했다', xp: 800, tier: 'mythic' },
  { id: 'git_branch_500', icon: '🍃', title: '잎새의 바다', subtitle: '500개 이상 다른 브랜치에서 작업했다', xp: 1500, tier: 'mythic' },
  { id: 'git_master_200', icon: '💣', title: '핵폭발', subtitle: '한 세션에서 200개 이상 파일을 변경했다', xp: 800, tier: 'mythic' },
  { id: 'git_master_500', icon: '🌪️', title: '카테고리 5', subtitle: '한 세션에서 500개 이상 파일을 변경했다', xp: 1500, tier: 'mythic' },
  { id: 'file_surgeon_50', icon: '🧑‍⚕️', title: '신의 손', subtitle: '한 세션에서 50개 이상 파일을 수정했다', xp: 700, tier: 'mythic' },
  { id: 'file_surgeon_100', icon: '🧪', title: '연금술사', subtitle: '한 세션에서 100개 이상 파일을 수정했다', xp: 1200, tier: 'mythic' },
  { id: 'night_owl_100', icon: '👻', title: '유령', subtitle: '심야 작업을 100일 이상 했다', xp: 800, tier: 'mythic' },
  { id: 'night_owl_365', icon: '🧛', title: '뱀파이어', subtitle: '심야 작업을 365일 이상 했다', xp: 2000, tier: 'mythic' },
  { id: 'session_streak_365_x2', icon: '⏳', title: '시간의 군주', subtitle: '730일(2년) 연속으로 작업했다', xp: 3000, tier: 'mythic' },
  { id: 'session_streak_1000', icon: '🏺', title: '영원', subtitle: '1,000일 연속으로 작업했다', xp: 5000, tier: 'mythic' },
  { id: 'marathon_24h', icon: '🌅', title: '해가 뜨고 지고', subtitle: '24시간 이상 연속으로 작업했다', xp: 1000, tier: 'mythic' },
  { id: 'marathon_48h', icon: '😵', title: '불면의 경지', subtitle: '48시간 이상 연속으로 작업했다', xp: 2000, tier: 'mythic' },
  { id: 'weekend_100', icon: '🎡', title: '영원한 주말', subtitle: '주말에 100일 이상 작업했다', xp: 800, tier: 'mythic' },
  { id: 'weekend_365', icon: '🏖️', title: '워커홀릭', subtitle: '주말에 365일 이상 작업했다', xp: 2000, tier: 'mythic' },
  { id: 'multi_10', icon: '🎼', title: '오케스트라', subtitle: '10개 이상 동시에 작업했다', xp: 800, tier: 'mythic' },
  { id: 'multi_15', icon: '🎆', title: '불꽃놀이', subtitle: '15개 이상 동시에 작업했다', xp: 1500, tier: 'mythic' },
  { id: 'level_25', icon: '🔱', title: '포세이돈', subtitle: '레벨 25에 도달했다', xp: 1000, tier: 'mythic' },
  { id: 'level_30', icon: '⚡', title: '제우스', subtitle: '레벨 30에 도달했다', xp: 2000, tier: 'mythic' },
  { id: 'level_50', icon: '🕊️', title: '신', subtitle: '레벨 50에 도달했다', xp: 5000, tier: 'mythic' },
  { id: 'active_days_365', icon: '📅', title: '개근상', subtitle: '누적 365일 작업했다', xp: 1000, tier: 'mythic' },
  { id: 'active_days_1000', icon: '🗓️', title: '천일의 약속', subtitle: '누적 1,000일 작업했다', xp: 2500, tier: 'mythic' },
  { id: 'tuesday_coder', icon: '📌', title: '화요일 전사', subtitle: '화요일에 작업했다', xp: 25, tier: 'common' },
  { id: 'wednesday_coder', icon: '🐫', title: '수요일 낙타', subtitle: '수요일에 작업했다', xp: 25, tier: 'common' },
  { id: 'thursday_coder', icon: '⚡', title: '목요일 번개', subtitle: '목요일에 작업했다', xp: 25, tier: 'common' },
  { id: 'first_grep', icon: '🔎', title: '첫 검색', subtitle: '첫 Grep 검색을 실행했다', xp: 20, tier: 'common' },
  { id: 'first_glob', icon: '📂', title: '파일 탐색가', subtitle: '첫 Glob 패턴 검색을 실행했다', xp: 20, tier: 'common' },
  { id: 'command_25', icon: '🎯', title: '스물다섯 발', subtitle: '명령을 25번 실행했다', xp: 25, tier: 'common' },
  { id: 'complete_3', icon: '🥉', title: '동메달', subtitle: '작업을 3번 완료했다', xp: 25, tier: 'common' },
  { id: 'session_3', icon: '🔰', title: '세 번째 출근', subtitle: '세션을 3번 시작했다', xp: 20, tier: 'common' },
  { id: 'session_5', icon: '✋', title: '다섯 번째 출근', subtitle: '세션을 5번 시작했다', xp: 25, tier: 'common' },
  { id: 'read_5', icon: '📄', title: '열람자', subtitle: '한 세션에서 파일을 5번 읽었다', xp: 20, tier: 'common' },
  { id: 'afternoon_coder', icon: '☕', title: '오후의 커피', subtitle: '오후 2~4시에 작업했다', xp: 40, tier: 'rare' },
  { id: 'evening_coder', icon: '🌆', title: '석양의 코더', subtitle: '저녁 6~8시에 작업했다', xp: 40, tier: 'rare' },
  { id: 'dinner_coder', icon: '🍽️', title: '저녁밥 거른 코더', subtitle: '저녁 7시에 작업 중이었다', xp: 45, tier: 'rare' },
  { id: 'command_75', icon: '7️⃣', title: '일흔다섯', subtitle: '명령을 75번 실행했다', xp: 45, tier: 'rare' },
  { id: 'command_200', icon: '🔢', title: '이백장군', subtitle: '명령을 200번 실행했다', xp: 50, tier: 'rare' },
  { id: 'complete_15', icon: '🏐', title: '열다섯 번째', subtitle: '작업을 15번 완료했다', xp: 45, tier: 'rare' },
  { id: 'complete_20', icon: '🎱', title: '스무 번째', subtitle: '작업을 20번 완료했다', xp: 45, tier: 'rare' },
  { id: 'token_2k_total', icon: '🪙', title: '이천 토큰', subtitle: '누적 2,000 토큰을 사용했다', xp: 35, tier: 'rare' },
  { id: 'token_5k_total', icon: '🏷️', title: '오천 토큰', subtitle: '누적 5,000 토큰을 사용했다', xp: 40, tier: 'rare' },
  { id: 'token_2k_session', icon: '📋', title: '보통 세션', subtitle: '한 세션에서 2k 이상 토큰을 사용했다', xp: 35, tier: 'rare' },
  { id: 'cost_2', icon: '💲', title: '두 번째 달러', subtitle: '누적 비용 $2를 넘었다', xp: 40, tier: 'rare' },
  { id: 'cost_3', icon: '💲', title: '세 번째 달러', subtitle: '누적 비용 $3을 넘었다', xp: 40, tier: 'rare' },
  { id: 'focus_15', icon: '⏱️', title: '집중 15분', subtitle: '15분 이상 연속 작업했다', xp: 35, tier: 'rare' },
  { id: 'focus_45', icon: '⏰', title: '집중 45분', subtitle: '45분 이상 연속 작업했다', xp: 50, tier: 'rare' },
  { id: 'file_edit_10', icon: '📑', title: '열 번 수정', subtitle: '파일을 10번 수정했다', xp: 35, tier: 'rare' },
  { id: 'file_edit_15', icon: '📋', title: '열다섯 번 수정', subtitle: '파일을 15번 수정했다', xp: 40, tier: 'rare' },
  { id: 'read_25', icon: '📖', title: '다독가', subtitle: '파일을 25번 읽었다', xp: 40, tier: 'rare' },
  { id: 'read_100', icon: '🔬', title: '연구자', subtitle: '파일을 100번 읽었다', xp: 50, tier: 'rare' },
  { id: 'git_branch_3', icon: '🌿', title: '세 갈래', subtitle: '3개 이상 다른 브랜치에서 작업했다', xp: 40, tier: 'rare' },
  { id: 'error_3', icon: '🤕', title: '세 번의 시련', subtitle: '에러에서 3번 복구했다', xp: 40, tier: 'rare' },
  { id: 'session_15', icon: '📝', title: '열다섯 번째 출근', subtitle: '세션을 15번 시작했다', xp: 40, tier: 'rare' },
  { id: 'session_20', icon: '📊', title: '스무 번째 출근', subtitle: '세션을 20번 시작했다', xp: 40, tier: 'rare' },
  { id: 'night_owl_3', icon: '🌒', title: '초승달', subtitle: '심야 작업을 3일 이상 했다', xp: 45, tier: 'rare' },
  { id: 'night_owl_5', icon: '🌓', title: '반달', subtitle: '심야 작업을 5일 이상 했다', xp: 50, tier: 'rare' },
  { id: 'weekend_5', icon: '🏠', title: '주말 상근자', subtitle: '주말에 5일 이상 작업했다', xp: 45, tier: 'rare' },
  { id: 'weekend_10', icon: '🏡', title: '주말 단골', subtitle: '주말에 10일 이상 작업했다', xp: 50, tier: 'rare' },
  { id: 'complete_75', icon: '🎖️', title: '상사', subtitle: '작업을 75번 완료했다', xp: 85, tier: 'epic' },
  { id: 'complete_150', icon: '🥇', title: '금메달', subtitle: '작업을 150번 완료했다', xp: 90, tier: 'epic' },
  { id: 'complete_250', icon: '🏆', title: '트로피', subtitle: '작업을 250번 완료했다', xp: 90, tier: 'epic' },
  { id: 'command_750', icon: '🗡️', title: '칠백오십', subtitle: '명령을 750번 실행했다', xp: 85, tier: 'epic' },
  { id: 'command_1500', icon: '🔱', title: '천오백', subtitle: '명령을 1,500번 실행했다', xp: 90, tier: 'epic' },
  { id: 'command_3000', icon: '⚔️', title: '삼천검', subtitle: '명령을 3,000번 실행했다', xp: 95, tier: 'epic' },
  { id: 'command_7500', icon: '🪓', title: '벌목꾼', subtitle: '명령을 7,500번 실행했다', xp: 100, tier: 'epic' },
  { id: 'session_30', icon: '📅', title: '한 달 근무', subtitle: '세션을 30번 시작했다', xp: 80, tier: 'epic' },
  { id: 'session_40', icon: '📆', title: '사십 번 출근', subtitle: '세션을 40번 시작했다', xp: 80, tier: 'epic' },
  { id: 'token_20k_session', icon: '🐬', title: '돌고래', subtitle: '한 세션에서 20k 이상 토큰을 사용했다', xp: 85, tier: 'epic' },
  { id: 'token_30k_session', icon: '🦭', title: '바다표범', subtitle: '한 세션에서 30k 이상 토큰을 사용했다', xp: 85, tier: 'epic' },
  { id: 'token_200k_total', icon: '🏪', title: '토큰 상점', subtitle: '누적 200,000 토큰을 사용했다', xp: 90, tier: 'epic' },
  { id: 'token_300k_total', icon: '🏬', title: '토큰 백화점', subtitle: '누적 300,000 토큰을 사용했다', xp: 90, tier: 'epic' },
  { id: 'cost_20', icon: '💳', title: 'VIP', subtitle: '누적 비용 $20을 넘었다', xp: 85, tier: 'epic' },
  { id: 'cost_30', icon: '💎', title: '다이아 회원', subtitle: '누적 비용 $30을 넘었다', xp: 90, tier: 'epic' },
  { id: 'cost_75', icon: '🏅', title: '골드 후원자', subtitle: '누적 비용 $75를 넘었다', xp: 95, tier: 'epic' },
  { id: 'file_edit_75', icon: '📐', title: '설계사', subtitle: '파일을 75번 수정했다', xp: 80, tier: 'epic' },
  { id: 'file_edit_150', icon: '🔧', title: '기술자', subtitle: '파일을 150번 수정했다', xp: 85, tier: 'epic' },
  { id: 'read_150', icon: '📜', title: '고문서 해독가', subtitle: '파일을 150번 읽었다', xp: 80, tier: 'epic' },
  { id: 'read_300', icon: '🏛️', title: '도서관장', subtitle: '파일을 300번 읽었다', xp: 85, tier: 'epic' },
  { id: 'error_15', icon: '🩹', title: '응급처치', subtitle: '에러에서 15번 복구했다', xp: 85, tier: 'epic' },
  { id: 'error_20', icon: '🧯', title: '소방관', subtitle: '에러에서 20번 복구했다', xp: 90, tier: 'epic' },
  { id: 'error_35', icon: '🧱', title: '성벽', subtitle: '에러에서 35번 복구했다', xp: 95, tier: 'epic' },
  { id: 'git_branch_7', icon: '🌵', title: '선인장', subtitle: '7개 이상 다른 브랜치에서 작업했다', xp: 80, tier: 'epic' },
  { id: 'git_branch_15', icon: '🏝️', title: '군도', subtitle: '15개 이상 다른 브랜치에서 작업했다', xp: 90, tier: 'epic' },
  { id: 'git_branch_20', icon: '🗺️', title: '지도 제작자', subtitle: '20개 이상 다른 브랜치에서 작업했다', xp: 90, tier: 'epic' },
  { id: 'session_streak_5', icon: '🔥', title: '5일 연속', subtitle: '5일 연속으로 작업했다', xp: 85, tier: 'epic' },
  { id: 'session_streak_10', icon: '🔥', title: '10일 연속', subtitle: '10일 연속으로 작업했다', xp: 90, tier: 'epic' },
  { id: 'session_streak_21', icon: '📿', title: '3주 연속', subtitle: '21일 연속으로 작업했다', xp: 100, tier: 'epic' },
  { id: 'night_owl_15', icon: '🦇', title: '15일의 밤', subtitle: '심야 작업을 15일 이상 했다', xp: 90, tier: 'epic' },
  { id: 'night_owl_20', icon: '🌑', title: '그믐달', subtitle: '심야 작업을 20일 이상 했다', xp: 95, tier: 'epic' },
  { id: 'night_owl_30', icon: '🌘', title: '한 달의 밤', subtitle: '심야 작업을 30일 이상 했다', xp: 100, tier: 'epic' },
  { id: 'weekend_20', icon: '🎢', title: '주말 마니아', subtitle: '주말에 20일 이상 작업했다', xp: 85, tier: 'epic' },
  { id: 'weekend_30', icon: '🎠', title: '주말의 왕', subtitle: '주말에 30일 이상 작업했다', xp: 90, tier: 'epic' },
  { id: 'active_days_30', icon: '📅', title: '한 달 개근', subtitle: '누적 30일 작업했다', xp: 80, tier: 'epic' },
  { id: 'active_days_60', icon: '📆', title: '두 달 개근', subtitle: '누적 60일 작업했다', xp: 85, tier: 'epic' },
  { id: 'active_days_90', icon: '🗓️', title: '분기 개근', subtitle: '누적 90일 작업했다', xp: 90, tier: 'epic' },
  { id: 'active_days_180', icon: '📊', title: '반년 개근', subtitle: '누적 180일 작업했다', xp: 95, tier: 'epic' },
  { id: 'marathon_2h', icon: '🏃‍♂️', title: '하프 마라톤', subtitle: '2시간 이상 연속으로 작업했다', xp: 90, tier: 'epic' },
  { id: 'marathon_4h', icon: '🏃‍♀️', title: '풀 마라톤', subtitle: '4시간 이상 연속으로 작업했다', xp: 100, tier: 'epic' },
  { id: 'marathon_8h', icon: '🏋️', title: '철인', subtitle: '8시간 이상 연속으로 작업했다', xp: 110, tier: 'epic' },
  { id: 'complete_400', icon: '🎪', title: '서커스 단장', subtitle: '작업을 400번 완료했다', xp: 200, tier: 'legendary' },
  { id: 'complete_750', icon: '🏰', title: '성주', subtitle: '작업을 750번 완료했다', xp: 250, tier: 'legendary' },
  { id: 'command_15000', icon: '🗼', title: '탑 빌더', subtitle: '명령을 15,000번 실행했다', xp: 350, tier: 'legendary' },
  { id: 'command_25000', icon: '🏗️', title: '크레인', subtitle: '명령을 25,000번 실행했다', xp: 400, tier: 'legendary' },
  { id: 'session_150', icon: '🏭', title: '공장장', subtitle: '세션을 150번 시작했다', xp: 200, tier: 'legendary' },
  { id: 'session_200', icon: '🏛️', title: '의회', subtitle: '세션을 200번 시작했다', xp: 250, tier: 'legendary' },
  { id: 'session_300', icon: '🌆', title: '메트로폴리스', subtitle: '세션을 300번 시작했다', xp: 300, tier: 'legendary' },
  { id: 'session_1000', icon: '🌃', title: '네온시티', subtitle: '세션을 1,000번 시작했다', xp: 400, tier: 'legendary' },
  { id: 'token_2million', icon: '🌏', title: '대륙', subtitle: '누적 2,000,000 토큰을 사용했다', xp: 300, tier: 'legendary' },
  { id: 'token_3million', icon: '🌎', title: '서반구', subtitle: '누적 3,000,000 토큰을 사용했다', xp: 350, tier: 'legendary' },
  { id: 'cost_200', icon: '💰', title: '금고', subtitle: '누적 비용 $200을 넘었다', xp: 250, tier: 'legendary' },
  { id: 'cost_300', icon: '🏧', title: 'ATM', subtitle: '누적 비용 $300을 넘었다', xp: 300, tier: 'legendary' },
  { id: 'file_edit_750', icon: '⛏️', title: '광산 노동자', subtitle: '파일을 750번 수정했다', xp: 250, tier: 'legendary' },
  { id: 'read_750', icon: '🔭', title: '천문학자', subtitle: '파일을 750번 읽었다', xp: 250, tier: 'legendary' },
  { id: 'error_75', icon: '🛡️', title: '강철 방패', subtitle: '에러에서 75번 복구했다', xp: 200, tier: 'legendary' },
  { id: 'weekend_75', icon: '🎡', title: '놀이공원 사장', subtitle: '주말에 75일 이상 작업했다', xp: 350, tier: 'legendary' },
  { id: 'active_days_270', icon: '🗺️', title: '세계 일주', subtitle: '누적 270일 작업했다', xp: 300, tier: 'legendary' },
  { id: 'session_streak_45', icon: '🧲', title: '45일 연속', subtitle: '45일 연속으로 작업했다', xp: 350, tier: 'legendary' },
  { id: 'session_streak_90', icon: '💫', title: '분기 연속', subtitle: '90일 연속으로 작업했다', xp: 400, tier: 'legendary' },
  { id: 'marathon_10h', icon: '🏜️', title: '사하라 횡단', subtitle: '10시간 이상 연속으로 작업했다', xp: 400, tier: 'legendary' },
  { id: 'level_12', icon: '🌟', title: '빛나는 별', subtitle: '레벨 12에 도달했다', xp: 300, tier: 'legendary' },
  { id: 'complete_7500', icon: '🐉', title: '용의 둥지', subtitle: '작업을 7,500번 완료했다', xp: 1200, tier: 'mythic' },
  { id: 'complete_15000', icon: '🕳️', title: '차원의 문', subtitle: '작업을 15,000번 완료했다', xp: 2000, tier: 'mythic' },
  { id: 'complete_25000', icon: '🌌', title: '다중 우주', subtitle: '작업을 25,000번 완료했다', xp: 3000, tier: 'mythic' },
  { id: 'command_200000', icon: '🌀', title: '소용돌이', subtitle: '명령을 200,000번 실행했다', xp: 1500, tier: 'mythic' },
  { id: 'command_1000000', icon: '♾️', title: '백만장자 명령', subtitle: '명령을 1,000,000번 실행했다', xp: 3000, tier: 'mythic' },
  { id: 'session_20000', icon: '🌠', title: '유성우', subtitle: '세션을 20,000번 시작했다', xp: 2000, tier: 'mythic' },
  { id: 'token_500million', icon: '🌟', title: '퀘이사', subtitle: '누적 500,000,000 토큰을 사용했다', xp: 2000, tier: 'mythic' },
  { id: 'token_2m_session', icon: '🌊', title: '해일', subtitle: '한 세션에서 2M 이상 토큰을 사용했다', xp: 1500, tier: 'mythic' },
  { id: 'token_5m_session', icon: '🌋', title: '슈퍼볼케이노', subtitle: '한 세션에서 5M 이상 토큰을 사용했다', xp: 2500, tier: 'mythic' },
  { id: 'cost_25000', icon: '🏰', title: '왕궁', subtitle: '누적 비용 $25,000을 넘었다', xp: 2000, tier: 'mythic' },
  { id: 'cost_100000', icon: '🌍', title: '국가 예산', subtitle: '누적 비용 $100,000을 넘었다', xp: 5000, tier: 'mythic' },
  { id: 'file_edit_20000', icon: '🌪️', title: '허리케인', subtitle: '파일을 20,000번 수정했다', xp: 2000, tier: 'mythic' },
  { id: 'file_edit_100000', icon: '🌊', title: '대양', subtitle: '파일을 100,000번 수정했다', xp: 3000, tier: 'mythic' },
  { id: 'read_20000', icon: '🧿', title: '만물의 눈', subtitle: '파일을 20,000번 읽었다', xp: 1500, tier: 'mythic' },
  { id: 'read_100000', icon: '📡', title: '딥 스페이스', subtitle: '파일을 100,000번 읽었다', xp: 2500, tier: 'mythic' },
  { id: 'error_2000', icon: '⚛️', title: '핵융합', subtitle: '에러에서 2,000번 복구했다', xp: 3000, tier: 'mythic' },
  { id: 'git_branch_200', icon: '🌳', title: '아마존', subtitle: '200개 이상 다른 브랜치에서 작업했다', xp: 1200, tier: 'mythic' },
  { id: 'git_branch_1000', icon: '🌲', title: '타이가', subtitle: '1,000개 이상 다른 브랜치에서 작업했다', xp: 2500, tier: 'mythic' },
  { id: 'git_master_1000', icon: '💫', title: '초신성', subtitle: '한 세션에서 1,000개 이상 파일을 변경했다', xp: 2000, tier: 'mythic' },
  { id: 'file_surgeon_200', icon: '🧬', title: '유전자 편집', subtitle: '한 세션에서 200개 이상 파일을 수정했다', xp: 1500, tier: 'mythic' },
  { id: 'weekend_500', icon: '🏗️', title: '영원한 건설', subtitle: '주말에 500일 이상 작업했다', xp: 2500, tier: 'mythic' },
  { id: 'active_days_2000', icon: '🗿', title: '모아이', subtitle: '누적 2,000일 작업했다', xp: 3000, tier: 'mythic' },
  { id: 'active_days_3650', icon: '🏺', title: '십년의 유산', subtitle: '누적 3,650일(10년) 작업했다', xp: 5000, tier: 'mythic' },
  { id: 'session_streak_500', icon: '🧊', title: '빙하기', subtitle: '500일 연속으로 작업했다', xp: 3000, tier: 'mythic' },
  { id: 'session_streak_1500', icon: '🏛️', title: '문명', subtitle: '1,500일 연속으로 작업했다', xp: 5000, tier: 'mythic' },
  { id: 'marathon_72h', icon: '💀', title: '불멸', subtitle: '72시간 이상 연속으로 작업했다', xp: 3000, tier: 'mythic' },
  { id: 'level_40', icon: '🔮', title: '대마법사', subtitle: '레벨 40에 도달했다', xp: 3000, tier: 'mythic' },
  { id: 'level_75', icon: '👁️', title: '전지전능', subtitle: '레벨 75에 도달했다', xp: 5000, tier: 'mythic' },
  { id: 'level_100', icon: '🕊️', title: '아센션', subtitle: '레벨 100에 도달했다', xp: 10000, tier: 'mythic' },
  { id: 'mythic_perfectionist', icon: '🌈', title: '전설을 넘어서', subtitle: '전설 등급 이하 모든 업적을 달성했다', xp: 3000, tier: 'mythic' },
  { id: 'true_god', icon: '∞', title: '초월', subtitle: '신화 등급 외 모든 업적을 달성했다', xp: 10000, tier: 'mythic' }
];

export const macFurnitureCatalog: MacFurnitureDefinition[] = [
  { id: 'sofa', name: '소파', icon: 'sofa.fill', width: 49, height: 30, isWallItem: false, requiredLevel: null, requiredAchievement: null },
  { id: 'sideTable', name: '사이드테이블', icon: 'table.furniture.fill', width: 18, height: 14, isWallItem: false, requiredLevel: null, requiredAchievement: null },
  { id: 'coffeeMachine', name: '커피머신', icon: 'cup.and.saucer.fill', width: 16, height: 28, isWallItem: false, requiredLevel: null, requiredAchievement: null },
  { id: 'plant', name: '화분', icon: 'leaf.fill', width: 14, height: 28, isWallItem: false, requiredLevel: null, requiredAchievement: null },
  { id: 'picture', name: '액자', icon: 'photo.artframe', width: 20, height: 16, isWallItem: true, requiredLevel: null, requiredAchievement: null },
  { id: 'neonSign', name: '네온간판', icon: 'lightbulb.fill', width: 64, height: 16, isWallItem: true, requiredLevel: null, requiredAchievement: null },
  { id: 'rug', name: '러그', icon: 'rectangle.fill', width: 100, height: 14, isWallItem: false, requiredLevel: null, requiredAchievement: null },
  { id: 'bookshelf', name: '책장', icon: 'books.vertical.fill', width: 20, height: 36, isWallItem: false, requiredLevel: 5, requiredAchievement: null },
  { id: 'aquarium', name: '수족관', icon: 'fish.fill', width: 22, height: 18, isWallItem: false, requiredLevel: 8, requiredAchievement: null },
  { id: 'arcade', name: '오락기', icon: 'gamecontroller.fill', width: 16, height: 30, isWallItem: false, requiredLevel: 10, requiredAchievement: 'complete_50' },
  { id: 'whiteboard', name: '화이트보드', icon: 'rectangle.and.pencil.and.ellipsis', width: 30, height: 22, isWallItem: true, requiredLevel: 7, requiredAchievement: null },
  { id: 'lamp', name: '스탠드 조명', icon: 'lamp.floor.fill', width: 10, height: 30, isWallItem: false, requiredLevel: 3, requiredAchievement: null },
  { id: 'cat', name: '고양이', icon: 'cat.fill', width: 12, height: 10, isWallItem: false, requiredLevel: 15, requiredAchievement: 'night_owl_10' },
  { id: 'tv', name: 'TV', icon: 'tv.fill', width: 28, height: 18, isWallItem: true, requiredLevel: 12, requiredAchievement: null },
  { id: 'fan', name: '선풍기', icon: 'fan.fill', width: 12, height: 22, isWallItem: false, requiredLevel: 6, requiredAchievement: null },
  { id: 'calendar', name: '달력', icon: 'calendar', width: 14, height: 14, isWallItem: true, requiredLevel: 4, requiredAchievement: null },
  { id: 'poster', name: '포스터', icon: 'doc.richtext.fill', width: 16, height: 20, isWallItem: true, requiredLevel: 9, requiredAchievement: null },
  { id: 'trashcan', name: '휴지통', icon: 'trash.fill', width: 10, height: 12, isWallItem: false, requiredLevel: 2, requiredAchievement: null },
  { id: 'cushion', name: '쿠션', icon: 'circle.fill', width: 12, height: 8, isWallItem: false, requiredLevel: null, requiredAchievement: null }
];

export const macBackgroundCatalog: MacBackgroundDefinition[] = [
  { id: 'auto', label: '자동', icon: 'sparkles', requiredLevel: null },
  { id: 'sunny', label: '맑은 낮', icon: 'sun.max.fill', requiredLevel: null },
  { id: 'clearSky', label: '푸른 하늘', icon: 'cloud.sun.fill', requiredLevel: null },
  { id: 'sunset', label: '노을', icon: 'sunset.fill', requiredLevel: null },
  { id: 'goldenHour', label: '골든아워', icon: 'sun.haze.fill', requiredLevel: 3 },
  { id: 'dusk', label: '황혼', icon: 'sun.horizon.fill', requiredLevel: 3 },
  { id: 'moonlit', label: '달빛', icon: 'moon.fill', requiredLevel: null },
  { id: 'starryNight', label: '별밤', icon: 'star.fill', requiredLevel: 5 },
  { id: 'aurora', label: '오로라', icon: 'wand.and.stars', requiredLevel: 12 },
  { id: 'milkyWay', label: '은하수', icon: 'sparkles', requiredLevel: 15 },
  { id: 'storm', label: '폭풍', icon: 'cloud.bolt.fill', requiredLevel: 10 },
  { id: 'rain', label: '비', icon: 'cloud.rain.fill', requiredLevel: null },
  { id: 'snow', label: '눈', icon: 'cloud.snow.fill', requiredLevel: 8 },
  { id: 'fog', label: '안개', icon: 'cloud.fog.fill', requiredLevel: 5 },
  { id: 'cherryBlossom', label: '벚꽃', icon: 'leaf.fill', requiredLevel: 8 },
  { id: 'autumn', label: '가을', icon: 'leaf.fill', requiredLevel: 7 },
  { id: 'forest', label: '숲', icon: 'tree.fill', requiredLevel: 7 },
  { id: 'neonCity', label: '네온 시티', icon: 'building.2.fill', requiredLevel: 20 },
  { id: 'ocean', label: '오션', icon: 'water.waves', requiredLevel: 10 },
  { id: 'desert', label: '사막', icon: 'sun.max.fill', requiredLevel: 18 },
  { id: 'volcano', label: '화산', icon: 'mountain.2.fill', requiredLevel: 25 }
];
